"use client";
import {useEffect,useMemo,useState} from "react";
const CHANNELS=["Facebook","Instagram","TikTok","YouTube Shorts","LinkedIn"];
const key="hcdecor-publishing-demo-v1";
export default function PublishingCenter(){
 const [items,setItems]=useState([]),[title,setTitle]=useState(""),[caption,setCaption]=useState(""),[channels,setChannels]=useState(["Facebook","Instagram"]),[date,setDate]=useState(""),[time,setTime]=useState("09:00"),[tab,setTab]=useState("composer");
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(key)||"[]"))}catch{}},[]);
 const save=x=>{setItems(x);localStorage.setItem(key,JSON.stringify(x))};
 const toggle=c=>setChannels(x=>x.includes(c)?x.filter(v=>v!==c):[...x,c]);
 const create=()=>{if(!title.trim()||!date||!channels.length)return;const batch=Date.now();const jobs=channels.map((channel,i)=>({id:batch+i,title:title.trim(),caption:caption.trim(),channel,date,time,status:"Scheduled",createdAt:new Date().toISOString()}));save([...jobs,...items]);setTitle("");setCaption("");setTab("queue")};
 const remove=id=>save(items.filter(x=>x.id!==id));
 const counts=useMemo(()=>({jobs:items.length,scheduled:items.filter(x=>x.status==="Scheduled").length,channels:new Set(items.map(x=>x.channel)).size}),[items]);
 return <main className="pub"><aside className="pubSide"><a href="/hub" className="pubLogo"><b>HC</b>Decor HUB</a><small>PUBLISHING CENTER</small>{[["composer","✦ Composer"],["queue","▤ Queue"],["calendar","▦ Calendar"],["channels","◉ Channel Groups"],["logs","≡ Logs"]].map(([k,n])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{n}</button>)}<hr/><a href="/hub/workflows">⌘ Workflow Builder</a><a href="/hub/review">✓ Review Center</a><a href="/hub">← Automation HUB</a></aside>
 <section className="pubMain"><header><div><small>HCDECOR / CONTENT OPERATIONS</small><h1>Publishing Center</h1></div><div className="pubKpis"><span><b>{counts.jobs}</b> Jobs</span><span><b>{counts.scheduled}</b> Scheduled</span><span><b>{counts.channels}</b> Channels</span></div></header>
 <div className="pubDemo">RUN-READY DEMO · Lịch được lưu thật trong trình duyệt này. Chưa gửi ra mạng xã hội cho tới khi OAuth/API được kết nối.</div>
 {tab==="composer"&&<div className="pubGrid"><section className="pubCard"><h2>1. Content Source</h2><label>Tiêu đề<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="VD: Dự án mặt dựng HCDecor"/></label><label>Caption / nội dung<textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Nội dung gốc. Sau này AI Adapt tạo biến thể theo từng kênh."/></label><div className="pubSource"><button>＋ Project</button><button>＋ Drive Media</button><button>＋ WordPress</button><button>＋ Direct Post</button></div></section>
 <section className="pubCard"><h2>2. Channel Group</h2><div className="pubChannels">{CHANNELS.map(c=><button key={c} onClick={()=>toggle(c)} className={channels.includes(c)?"selected":""}>{channels.includes(c)?"✓ ":""}{c}</button>)}</div><h2>3. Schedule</h2><div className="pubWhen"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></div><button className="pubPrimary" disabled={!title.trim()||!date||!channels.length} onClick={create}>Create {channels.length} Publishing Jobs</button></section>
 <section className="pubCard pubPreview"><h2>Preview / Customize</h2>{channels.map(c=><article key={c}><b>{c}</b><strong>{title||"Tiêu đề nội dung"}</strong><p>{caption||"Caption sẽ hiển thị ở đây. Có thể tùy biến riêng cho từng nền tảng ở bước tiếp theo."}</p><small>{date||"Chưa chọn ngày"} · {time}</small></article>)}</section></div>}
 {tab==="queue"&&<section className="pubCard"><div className="pubHead"><h2>Publishing Queue</h2><button onClick={()=>save([])}>Xóa Demo Queue</button></div>{!items.length?<p>Chưa có job. Vào Composer để tạo Bulk Schedule.</p>:<table><thead><tr><th>Nội dung</th><th>Kênh</th><th>Lịch</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.channel}</td><td>{x.date} {x.time}</td><td><mark>{x.status}</mark></td><td><button onClick={()=>remove(x.id)}>×</button></td></tr>)}</tbody></table>}</section>}
 {tab==="calendar"&&<section className="pubCard"><h2>Bulk Schedule Calendar</h2><div className="pubCalendar">{[...new Set(items.map(x=>x.date))].sort().map(d=><article key={d}><b>{d}</b>{items.filter(x=>x.date===d).map(x=><span key={x.id}>{x.time} · {x.channel}<small>{x.title}</small></span>)}</article>)}</div>{!items.length&&<p>Chưa có lịch.</p>}</section>}
 {tab==="channels"&&<section className="pubCard"><h2>Channel Groups</h2><p><b>HCDecor Main</b> — Facebook · Instagram</p><p><b>Short Video</b> — TikTok · YouTube Shorts · Instagram</p><p><b>Professional</b> — LinkedIn · Website</p><div className="pubDemo">Các group hiện là preset UI. Credential/OAuth không được lưu trong trình duyệt.</div></section>}
 {tab==="logs"&&<section className="pubCard"><h2>Run / Audit Log</h2>{items.map(x=><p key={x.id}><b>{x.status}</b> · {x.channel} · {x.title} <small>{x.createdAt}</small></p>)}{!items.length&&<p>Chưa có log.</p>}</section>}
 </section></main>
}