"use client";
import {useState} from "react";
import * as XLSX from "xlsx";
function csv(text){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),split=s=>{const a=[];let q=false,v="";for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'&&s[i+1]==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){a.push(v.trim());v=""}else v+=c}a.push(v.trim());return a};if(lines.length<2)return [];const h=split(lines[0]);return lines.slice(1).map(x=>Object.fromEntries(split(x).map((v,i)=>[h[i]||("col_"+i),v])))}
export function DataCenterClient(){const [kind,setKind]=useState("products"),[source,setSource]=useState(""),[rows,setRows]=useState(""),[job,setJob]=useState(null),[msg,setMsg]=useState("Ready"),[preview,setPreview]=useState([]);
async function call(action,payload){setMsg("Working...");const r=await fetch("/api/commerce/admin-draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,payload})});const x=await r.json();setMsg(x.ok?"PASS":(x.error||"Failed"));return x}
function parse(){let x;try{x=rows.trim().startsWith("[")?JSON.parse(rows):csv(rows)}catch{return setMsg("Invalid CSV / JSON")};if(!Array.isArray(x)||!x.length)return setMsg("No rows");setPreview(x.slice(0,5));setMsg(x.length+" rows parsed");return x}
async function create(){const x=await call("import-job-create",{kind,source_type:"upload-or-paste",filename:source||"manual"});const j=x.data||x;if(x.ok)setJob(j)}
async function stage(){if(!job?.id)return setMsg("Create a draft job first");const parsed=parse();if(parsed)await call("import-job-stage",{id:job.id,rows:parsed})}
async function dry(){if(!job?.id)return setMsg("Create a draft job first");await call("import-job-dry-run",{id:job.id})}
async function state(to){if(!job?.id)return;const x=await call("import-job-state",{id:job.id,to});if(x.ok)setJob({...job,status:to})}
async function commit(){if(!job?.id)return;await call("import-job-commit",{id:job.id})}
async function rollback(){if(!job?.id)return;await call("import-job-rollback",{id:job.id})}
async function file(e){const f=e.target.files?.[0];if(!f)return;setSource(f.name);if(/\.xlsx?$/i.test(f.name)){try{const wb=XLSX.read(await f.arrayBuffer(),{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{defval:"",raw:false});if(!data.length)return setMsg("No rows in workbook");setRows(JSON.stringify(data,null,2));setPreview(data.slice(0,5));setMsg(data.length+" XLSX rows loaded · "+wb.SheetNames[0]);return}catch{return setMsg("Invalid XLSX workbook")}}setRows(await f.text());setMsg("File loaded")}
return <section className="panel"><div className="panelHead"><div><small>JOB WORKSPACE</small><h2>Production import workflow</h2></div><span className="status">{job?.status||"Draft"}</span></div><div className="commerceFormGrid"><label>Import type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="products">Products</option><option value="inventory">Inventory</option><option value="price">Price</option><option value="customers">Customers</option><option value="orders">Orders</option></select></label><label>CSV file<input type="file" accept=".csv,.txt,.xlsx,.xls" onChange={file}/></label><label>Source<input value={source} onChange={e=>setSource(e.target.value)} placeholder="Supplier / filename"/></label></div><label className="commerceWide">CSV or JSON rows<textarea rows="9" value={rows} onChange={e=>setRows(e.target.value)} placeholder={"name,sku,selling_price,on_hand\nProduct A,AMO-001,1000000,10"}/></label><div className="commerceActions"><button onClick={parse}>Preview</button><button onClick={create}>Create Job</button><button onClick={stage} disabled={!job?.id}>Map / Stage</button><button onClick={dry} disabled={!job?.id}>Validate / Dry Run</button><button onClick={()=>state("review")} disabled={!job?.id}>Review</button><button onClick={()=>state("approved")} disabled={job?.status!=="review"}>Approve</button><button onClick={commit} disabled={job?.status!=="approved"}>Commit</button><button onClick={rollback}>Rollback</button><small>{msg}{job?.id?" · "+job.id:""}</small></div>{preview.length>0&&<pre className="commerceCode">{JSON.stringify(preview,null,2)}</pre>}</section>}