const nav=[["⌂","Bảng điều khiển","/hub"],["▰","Projects","/hub/projects"],["◫","Media Manager","/hub/media"],["◎","CRM & Inbox","/hub/crm"],["✦","AI Providers","/hub/ai"],["⚙","Automation HUB","/hub/automation"],["⌘","Workflow Builder","/hub/workflows"],["✧","AI Agents","/hub/agents"],["▣","Lịch nội dung","/hub/calendar"],["▧","Review Center","/hub/review"],["◉","Web Publish","/hub/publish"],["◈","Social Accounts","/hub/social"],["◆","Integrations","/admin/integrations"],["●","Logs & Reports","/hub/reports"]];
const queue=[["#128","Phong cách Minimalist cho căn hộ hiện đại","Website · Facebook","25/09 09:00","Đang chờ"],["#127","5 mẹo decor phòng khách nhỏ mà sang trọng","Facebook · Instagram","25/09 10:30","Đang xử lý"],["#126","Bộ sưu tập nội thất gỗ tự nhiên","Website","25/09 14:00","Đã hoàn thành"],["#125","Xu hướng màu sắc 2025 trong thiết kế nội thất","TikTok · Instagram","26/09 08:00","Lỗi"],["#124","Không gian làm việc tại nhà","LinkedIn","26/09 10:00","Đang chờ"]];
const recipes=[["Đăng web → Auto Social","Khi Publish bài viết","Đăng Facebook, TikTok, Instagram",1],["Media mới → AI phân tích","Khi thêm media","Phân tích ảnh + gắn tag",1],["Bài cũ → Tái đăng","Theo lịch (hàng tuần)","Chọn bài cũ → đăng lại",1],["Form → Tạo Project","Khi có form submit","Tạo project + gửi AI",0],["Webhook → Tạo job","Khi nhận webhook","Tạo job theo dữ liệu",1],["Lên lịch tự động","Hàng ngày 08:00","Kiểm tra queue & xử lý",1]];
export default function Hub(){return <main className="refHub"><aside className="refSide"><div className="refBrand"><b>⌂</b><span>HCDecor HUB<small>CONTENT & AUTOMATION</small></span></div><nav>{nav.map(([i,n,u])=><a className={n==="Automation HUB"?"active":""} href={u} key={n}><i>{i}</i>{n}{n==="Review Center"&&<em>3</em>}</a>)}</nav><div className="refWp">WORDPRESS</div>{["Posts","Media","Pages","Comments","Appearance","Plugins","Users","Settings"].map(x=><a className="refExtra" key={x}>◆ {x}</a>)}</aside>
<section className="refMain"><div className="refTop"><div className="refSearch">⌕ &nbsp; Tìm projects, posts, media, lịch đăng... (Ctrl + K)</div><div><a className="refBlue" href="/contact">＋ Tạo mới</a><a className="refAdmin" href="/admin">Admin⌄</a></div></div>
<div className="refTitle"><div><h1>⚙ &nbsp;Automation HUB</h1><p>Tự động hóa toàn bộ quy trình từ nội dung → đăng web → phân phối đa kênh → tái sử dụng → báo cáo.</p></div><div className="refStats"><Stat n="12" t="Đang chờ"/><Stat n="5" t="Đang xử lý"/><Stat n="18" t="Đã hoàn thành"/><Stat n="2" t="Lỗi / Cần xử lý"/></div></div>
<div className="refWorkflow">{[["✓","Tạo nội dung","Project / Media"],["♟","AI xử lý","Văn bản + hình ảnh"],["▤","Review","& Phê duyệt"],["W","Đăng Web","WordPress"],["◆","Phân phối đa kênh","Facebook, TikTok, ..."],["♻","Evergreen","Tái sử dụng"],["▥","Báo cáo","Thống kê"]].map((x,i)=><article key={x[1]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span>{i<6&&<em>→</em>}</article>)}</div>
<div className="refGrid"><Panel title="↕ Hàng đợi tự động (Queue)" action="+ Tạo job"><div className="refTabs"><b>Tất cả (12)</b><span>Đang chờ (12)</span><span>Đang xử lý (5)</span><span>Lỗi (2)</span><span>Đã xong (18)</span></div><table><thead><tr><th>#</th><th>Nội dung / Tiêu đề</th><th>Kênh</th><th>Lịch đăng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{queue.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c}>{i===4?<mark className={"q"+i}>{c}</mark>:c}</td>)}<td>▶　✎　•••</td></tr>)}</tbody></table></Panel>
<Panel title="Lịch đăng (Calendar)" action="+ Thêm lịch"><div className="refCalHead"><b>Ngày　 <u>Tuần</u>　 Tháng</b><span>‹　 Tuần 25/09 - 01/10　 ›</span></div><div className="refCalendar">{["T2 25/09","T3 26/09","T4 27/09","T5 28/09","T6 29/09","T7 30/09","CN 01/10"].map((d,i)=><div key={d}><b>{d}</b>{i===0&&<small>09:00<br/>🌐 Minimalist...</small>}{i===1&&<small>10:00<br/>Facebook</small>}{i===3&&<small>10:30<br/>Xu hướng...</small>}{i===4&&<small>08:00<br/>YouTube</small>}{i===6&&<small>10:00<br/>Dự án thực tế</small>}</div>)}</div></Panel>
<Panel title="⚙ Quy tắc tự động (Automation Recipes)" action="+ Tạo quy tắc"><table><thead><tr><th>#</th><th>Tên quy tắc</th><th>Trigger (Khi nào)</th><th>Actions (Làm gì)</th><th>Bật/Tắt</th></tr></thead><tbody>{recipes.map((r,i)=><tr key={r[0]}><td>{i+1}</td><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className={r[3]?"refSwitch on":"refSwitch"}/></td></tr>)}</tbody></table></Panel>
<Panel title="↕ Thống kê & Báo cáo"><div className="refReport"><Stat n="35" t="Tổng bài đăng"/><Stat n="28" t="Đăng thành công"/><Stat n="5" t="Thất bại"/><Stat n="120K" t="Tổng lượt tiếp cận"/></div><div className="refBars"><i/><i/><i/><i/><i/><i/></div></Panel></div>
<Panel title="Luồng hoạt động tổng thể"><div className="refBottomFlow">{["1. Media / Project","2. AI xử lý","3. Review","4. Đăng Web","5. Phân phối đa kênh","6. Evergreen","7. Báo cáo"].map((x,i)=><article key={x}><b>{x}</b><p>{["Tải ảnh, tạo ý tưởng hoặc nhận từ form/webhook","Tạo nội dung, phân tích ảnh, gợi ý tiêu đề","Kiểm tra, chỉnh sửa, phê duyệt","Tự động tạo bài viết trên WordPress","Đăng theo lịch, quản lý trạng thái","Tự động chọn bài cũ đăng lại định kỳ","Thống kê, đo lường hiệu quả"][i]}</p></article>)}</div></Panel></section></main>}
function Panel({title,action,children}){return <section className="refPanel"><div className="refPanelHead"><h2>{title}</h2>{action&&<button>{action}</button>}</div>{children}</section>}
function Stat({n,t}){return <div className="refStat"><b>{n}</b><small>{t}</small></div>}
