import test from "node:test";import assert from "node:assert/strict";
import {DesktopWatchEngine} from "../core/desktop-watch-engine.js";
class Store{constructor(x){this.x=x}async list(){return this.x}async patch(id,p){const i=this.x.findIndex(v=>v.id===id);this.x[i]={...this.x[i],...p};return this.x[i]}}
test("watch detects change then stuck and sends once per epoch",async()=>{let now=0,hash="a",sends=0;const store=new Store([{id:"w",enabled:true,sourceType:"CHATGPT",chatAlias:"A",dispatchAlias:"A",autoSend:true,command:"iMaster next",stuckSec:1,cooldownSec:0,intervalSec:0}]);const e=new DesktopWatchEngine({store,now:()=>now,windowProvider:{},chatBridge:{snapshot:async()=>({online:true,busy:false,hash,assistant_tail:"working"}),send:async()=>{sends++;return {sent:true,status:"SENT"}}}});assert.equal((await e.tick())[0].state,"ACTIVE");now=1500;assert.equal((await e.tick())[0].state,"SENT");now=3000;assert.notEqual((await e.tick())[0].state,"SENT");assert.equal(sends,1);hash="b";now=4000;assert.equal((await e.tick())[0].state,"ACTIVE");now=5500;assert.equal((await e.tick())[0].state,"SENT");assert.equal(sends,2);});
test("busy exact chat never sends",async()=>{let sends=0;const store=new Store([{id:"w",enabled:true,sourceType:"CHATGPT",chatAlias:"A",dispatchAlias:"A",autoSend:true,stuckSec:0}]);const e=new DesktopWatchEngine({store,windowProvider:{},chatBridge:{snapshot:async()=>({online:true,busy:true,hash:"x"}),send:async()=>{sends++;return {sent:true}}}});assert.equal((await e.tick())[0].state,"BUSY");assert.equal(sends,0);});
test("native window watch can become stuck without unsafe send",async()=>{let now=0;const store=new Store([{id:"w",enabled:true,sourceType:"WINDOW",processName:"demo",titleContains:"work",autoSend:false,stuckSec:1,intervalSec:0}]);const e=new DesktopWatchEngine({store,now:()=>now,windowProvider:{list:async()=>[{id:1,hwnd:1,processName:"demo",title:"Work"}],capture:async()=>({hash:"same",path:"x.png"})},chatBridge:{}});await e.tick();now=1500;assert.equal((await e.tick())[0].state,"STUCK");});

test("watch interval skips early checks",async()=>{let now=0;const store=new Store([{id:"w",enabled:true,sourceType:"WINDOW",processName:"demo",titleContains:"work",autoSend:false,stuckSec:30,intervalSec:60}]);const e=new DesktopWatchEngine({store,now:()=>now,windowProvider:{list:async()=>[{id:1,hwnd:1,processName:"demo",title:"Work"}],capture:async()=>({hash:"x",path:"x.png"})},chatBridge:{}});assert.equal((await e.tick())[0].state,"ACTIVE");now=1000;const r=(await e.tick())[0];assert.equal(r.state,"WAITING");assert.equal(r.skipped,true);});

test("sent epoch becomes waiting response until chat output changes",async()=>{let now=0,hash="a",sends=0;const store=new Store([{id:"w",enabled:true,sourceType:"CHATGPT",chatAlias:"A",dispatchAlias:"A",autoSend:true,command:"iMaster next",stuckSec:1,cooldownSec:0,intervalSec:0}]);const e=new DesktopWatchEngine({store,now:()=>now,windowProvider:{},chatBridge:{snapshot:async()=>({online:true,busy:false,hash,assistant_tail:"working"}),send:async()=>{sends++;return {sent:true,status:"SENT"}}}});await e.tick();now=1500;assert.equal((await e.tick())[0].state,"SENT");now=2000;assert.equal((await e.tick())[0].state,"WAITING_RESPONSE");assert.equal(sends,1);hash="b";now=2500;assert.equal((await e.tick())[0].state,"ACTIVE");});

test("desktop watch logs only on state transition",async()=>{let now=0;const events=[];const store=new Store([{id:"w",enabled:true,sourceType:"WINDOW",processName:"demo",titleContains:"work",autoSend:false,stuckSec:1,intervalSec:0}]);const e=new DesktopWatchEngine({store,now:()=>now,logs:{append:async x=>events.push(x)},windowProvider:{list:async()=>[{id:1,hwnd:1,processName:"demo",title:"Work"}],capture:async()=>({hash:"same",path:"x.png"})},chatBridge:{}});await e.tick();now=1500;await e.tick();now=2500;await e.tick();assert.deepEqual(events.map(x=>x.message),["w ACTIVE","w STUCK"]);});

test("blocker-aware chat holds instead of auto-sending",async()=>{let sends=0;const store=new Store([{id:"w",enabled:true,sourceType:"CHATGPT",chatAlias:"A",dispatchAlias:"A",autoSend:true,command:"iMaster next",stuckSec:0,intervalSec:0}]);const e=new DesktopWatchEngine({store,windowProvider:{},chatBridge:{snapshot:async()=>({online:true,busy:false,hash:"x",assistant_tail:"CP2 WAITING_RESOURCE(HCDR)"}),send:async()=>{sends++;return {sent:true}}}});const r=(await e.tick())[0];assert.equal(r.state,"BLOCKER_HOLD");assert.equal(sends,0);});
