const KEY='hcdecor-admin-v4',PASS='971022';
const $=s=>document.querySelector(s);
const defaults={order:['home','services','projects','process','about'],visible:{home:true,services:true,projects:true,process:true,about:true},serviceTitle:'Giải pháp toàn diện',projectTitle:'Công trình & ý tưởng nổi bật',serviceImages:['https://iqrorwxhkmpnli5p.ldycdn.com/cloud/ppBplKnpljSRqlromllnkp/Illuminated-Lettering-At-Night.jpg','https://www.zenoxlighting.com/collections/decorative-lighting.jpg','https://storage.googleapis.com/enscape3d-production/images/000/000/252/lead/villa%202.png','https://framerusercontent.com/images/hX3zcGA1QPtJE4H36zeJeoVcQ.jpeg?height=1024&width=1024'],projectImages:['https://framerusercontent.com/images/hX3zcGA1QPtJE4H36zeJeoVcQ.jpeg?height=1024&width=1024','https://www.zenoxlighting.com/collections/decorative-lighting.jpg','https://iqrorwxhkmpnli5p.ldycdn.com/cloud/ppBplKnpljSRqlromllnkp/Illuminated-Lettering-At-Night.jpg']};
let state={...defaults,...safeLoad()},box=null,drag=null,history=[];
function safeLoad(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function login(){
 const pin=$('#pin'),v=(pin.value||'').trim();
 if(v!==PASS){pin.value='';pin.placeholder='Sai mật khẩu — nhập 971022';return false}
 $('#gate').style.display='none';$('#app').hidden=false;startAdmin();return false;
}
function startAdmin(){box=$('#modules');render();bindModules();bindControls();sendPreview()}
function snapshot(){history.push(JSON.stringify(state));if(history.length>20)history.shift()}
function read(){if(!box)return;state.order=[...box.children].map(x=>x.dataset.id);state.visible=Object.fromEntries([...box.children].map(x=>[x.dataset.id,x.querySelector('input[type=checkbox]').checked]));state.serviceTitle=$('#serviceTitle').value;state.projectTitle=$('#projectTitle').value;state.serviceImages=[...document.querySelectorAll('#serviceImages input')].map(x=>x.value);state.projectImages=[...document.querySelectorAll('#projectImages input')].map(x=>x.value)}
function save(){read();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){};const st=$('#status');st.textContent='Đã lưu';st.className='saved';sendPreview()}
function rows(sel,names,arr){const root=$(sel);root.innerHTML=names.map((n,i)=>'<label class="imgrow"><span>'+n+'</span><input value="'+String(arr[i]||'').replace(/"/g,'&quot;')+'"></label>').join('');root.querySelectorAll('input').forEach(x=>x.addEventListener('change',()=>{snapshot();save()}))}
function render(){state.order.forEach(id=>{const x=box.querySelector('[data-id="'+id+'"]');if(x)box.appendChild(x)});Object.entries(state.visible||{}).forEach(([id,v])=>{const x=box.querySelector('[data-id="'+id+'"] input');if(x)x.checked=v});$('#serviceTitle').value=state.serviceTitle||defaults.serviceTitle;$('#projectTitle').value=state.projectTitle||defaults.projectTitle;rows('#serviceImages',['Bảng hiệu','Nội thất','3D & Phối cảnh','Kiến trúc'],state.serviceImages||defaults.serviceImages);rows('#projectImages',['Kiến trúc','Nội thất','Bảng hiệu'],state.projectImages||defaults.projectImages)}
function bindModules(){[...box.children].forEach(el=>{el.addEventListener('dragstart',()=>{snapshot();drag=el;el.classList.add('dragging')});el.addEventListener('dragend',()=>{el.classList.remove('dragging');save()});el.querySelector('input').addEventListener('change',()=>{snapshot();save()})});box.addEventListener('dragover',e=>{e.preventDefault();if(!drag)return;const a=[...box.querySelectorAll('article:not(.dragging)')].find(x=>e.clientY<=x.getBoundingClientRect().top+x.offsetHeight/2);a?box.insertBefore(drag,a):box.appendChild(drag)})}
function bindControls(){['serviceTitle','projectTitle'].forEach(id=>$('#'+id).addEventListener('change',()=>{snapshot();save()}));$('#siteFrame').addEventListener('load',sendPreview);$('#refreshFrame').onclick=()=>$('#siteFrame').contentWindow.location.reload();$('#preview').onclick=()=>window.open('/?adminPreview=1','_blank');$('#publish').onclick=()=>{save();alert('Đã lưu bản chỉnh sửa.')};$('#undo').onclick=()=>{if(!history.length)return;state=JSON.parse(history.pop());render();save()};$('#logout').onclick=()=>location.reload()}
function sendPreview(){const f=$('#siteFrame');if(f&&f.contentWindow)f.contentWindow.postMessage({type:'hcdecor-preview',state},location.origin)}
document.addEventListener('DOMContentLoaded',()=>{const form=$('#login'),pin=$('#pin');form.addEventListener('submit',e=>{e.preventDefault();login()});form.querySelector('button').addEventListener('click',e=>{e.preventDefault();login()});pin.addEventListener('keyup',e=>{if(e.key==='Enter')login()});pin.focus()});