const KEY='hcdecor-admin-v5', $=s=>document.querySelector(s);
const defaults={order:['home','services','projects','process','about'],visible:{home:true,services:true,projects:true,process:true,about:true},heroTitle:'Thiết kế để thương hiệu được nhìn thấy.',heroLead:'Từ bảng hiệu, nội thất đến phối cảnh 3D — HCDecor biến ý tưởng thành trải nghiệm thương hiệu nhất quán.',heroCta:'Xem công trình',heroImage:'https://framerusercontent.com/images/hX3zcGA1QPtJE4H36zeJeoVcQ.jpeg?height=1400&width=1800',serviceTitle:'Giải pháp toàn diện',projectTitle:'Công trình & ý tưởng nổi bật',serviceImages:['https://iqrorwxhkmpnli5p.ldycdn.com/cloud/ppBplKnpljSRqlromllnkp/Illuminated-Lettering-At-Night.jpg','https://www.zenoxlighting.com/collections/decorative-lighting.jpg','https://storage.googleapis.com/enscape3d-production/images/000/000/252/lead/villa%202.png','https://framerusercontent.com/images/hX3zcGA1QPtJE4H36zeJeoVcQ.jpeg?height=1024&width=1024'],projectImages:['https://framerusercontent.com/images/hX3zcGA1QPtJE4H36zeJeoVcQ.jpeg?height=1024&width=1024','https://www.zenoxlighting.com/collections/decorative-lighting.jpg','https://iqrorwxhkmpnli5p.ldycdn.com/cloud/ppBplKnpljSRqlromllnkp/Illuminated-Lettering-At-Night.jpg']};
let state={...defaults,...loadStore()},box,history=[],drag;
function loadStore(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function startAdmin(){box=$('#modules');render();bind();preview()}
function snapshot(){history.push(JSON.stringify(state));if(history.length>30)history.shift()}
function read(){state.order=[...box.children].map(x=>x.dataset.id);state.visible=Object.fromEntries([...box.children].map(x=>[x.dataset.id,x.querySelector('input').checked]));['heroTitle','heroLead','heroCta','heroImage','serviceTitle','projectTitle'].forEach(id=>state[id]=$('#'+id).value);state.serviceImages=[...document.querySelectorAll('#serviceImages input')].map(x=>x.value);state.projectImages=[...document.querySelectorAll('#projectImages input')].map(x=>x.value)}
function save(){read();localStorage.setItem(KEY,JSON.stringify(state));$('#status').textContent='Đã lưu tự động';$('#status').className='saved';$('#editState').textContent='ĐÃ LƯU';preview()}
function rows(sel,names,arr){const root=$(sel);root.innerHTML=names.map((n,i)=>'<label class="imgrow"><span>'+n+'</span><input value="'+String(arr[i]||'').replace(/"/g,'&quot;')+'"></label>').join('');root.querySelectorAll('input').forEach(x=>x.oninput=changed)}
function render(){state.order.forEach(id=>{const el=box.querySelector('[data-id="'+id+'"]');if(el)box.appendChild(el)});Object.entries(state.visible).forEach(([id,v])=>{const x=box.querySelector('[data-id="'+id+'"] input');if(x)x.checked=v});['heroTitle','heroLead','heroCta','heroImage','serviceTitle','projectTitle'].forEach(id=>$('#'+id).value=state[id]||'');rows('#serviceImages',['Bảng hiệu','Nội thất','3D & Phối cảnh','Kiến trúc'],state.serviceImages);rows('#projectImages',['Kiến trúc','Nội thất','Bảng hiệu'],state.projectImages)}
let timer;function changed(){snapshot();$('#editState').textContent='ĐANG LƯU…';clearTimeout(timer);timer=setTimeout(save,350)}
function bind(){box.querySelectorAll('article').forEach(el=>{el.ondragstart=()=>{snapshot();drag=el};el.ondragend=()=>save();el.querySelector('input').onchange=changed});box.ondragover=e=>{e.preventDefault();if(!drag)return;const a=[...box.querySelectorAll('article')].find(x=>x!==drag&&e.clientY<x.getBoundingClientRect().top+x.offsetHeight/2);a?box.insertBefore(drag,a):box.appendChild(drag)};['heroTitle','heroLead','heroCta','heroImage','serviceTitle','projectTitle'].forEach(id=>$('#'+id).oninput=changed);$('#siteFrame').onload=preview;$('#refreshFrame').onclick=()=>$('#siteFrame').contentWindow.location.reload();$('#preview').onclick=()=>window.open('/?adminPreview=1','_blank');$('#desktop').onclick=()=>$('#siteFrame').className='desktop';$('#mobile').onclick=()=>$('#siteFrame').className='mobile';$('#publish').onclick=()=>{save();alert('Đã lưu bản chỉnh sửa')};$('#undo').onclick=()=>{if(!history.length)return;state=JSON.parse(history.pop());render();save()};document.querySelectorAll('.edit-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.edit-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const map={hero:'home',services:'services',projects:'projects',about:'about'};const f=$('#siteFrame');try{f.contentWindow.document.getElementById(map[b.dataset.target]).scrollIntoView({behavior:'smooth'})}catch(e){}})}
function preview(){const f=$('#siteFrame');if(f&&f.contentWindow)f.contentWindow.postMessage({type:'hcdecor-preview',state},location.origin)}
document.addEventListener('DOMContentLoaded',startAdmin);