const $=s=>document.querySelector(s),key='hcdecor_content_drafts_v2';let media=[],editing=null;
$('#media').onchange=e=>{media=[...e.target.files];$('#mediaList').innerHTML=media.map(f=>'<p>• '+esc(f.name)+' · '+Math.round(f.size/1024)+' KB</p>').join('')};
function data(){return{id:editing||Date.now(),idea:$('#idea').value.trim(),title:$('#title').value.trim(),caption:$('#caption').value.trim(),tags:$('#tags').value.trim(),channels:[...document.querySelectorAll('.channels input:checked')].map(x=>x.value),media:media.map(x=>x.name),workflow:($('#workflow')?.value||'Ý tưởng'),updated:new Date().toLocaleString('vi-VN')}}
function drafts(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return []}}
function store(a){localStorage.setItem(key,JSON.stringify(a.slice(0,50)))}
function renderPreview(){const d=data();$('#pTitle').textContent=d.title||d.idea||'Chưa có tiêu đề';$('#pCaption').textContent=d.caption||'Chưa có caption';$('#pTags').textContent=d.tags;const box=$('#pMedia');box.innerHTML='';if(media[0]){const u=URL.createObjectURL(media[0]),el=document.createElement(media[0].type.startsWith('video')?'video':'img');el.src=u;if(el.tagName==='VIDEO')el.controls=true;box.append(el)}}
function renderDrafts(){const a=drafts();$('#draftCount').textContent=a.length+' bản';$('#statTotal').textContent=a.length;$('#statReview').textContent=a.filter(x=>x.workflow==='Chờ duyệt').length;$('#statReady').textContent=a.filter(x=>x.workflow==='Sẵn sàng').length;$('#drafts').innerHTML=a.length?a.map(d=>'<div class="draft" data-id="'+d.id+'"><small>'+esc(d.updated)+'</small><b>'+esc(d.title||d.idea||'Bản nháp')+'</b><p>'+esc((d.channels||[]).join(' · ')||'Chưa chọn kênh')+'</p><div class="draft-actions"><button data-act="edit">Sửa</button><button data-act="copy">Nhân bản</button><button data-act="delete">Xóa</button></div></div>').join(''):'<p>Chưa có bản nháp.</p>'}
function load(d){editing=d.id;$('#idea').value=d.idea||'';$('#title').value=d.title||'';$('#caption').value=d.caption||'';$('#tags').value=d.tags||'';document.querySelectorAll('.channels input').forEach(x=>x.checked=(d.channels||[]).includes(x.value));if($('#workflow'))$('#workflow').value=d.workflow||'Ý tưởng';media=[];$('#mediaList').innerHTML=(d.media||[]).map(n=>'<p>• '+esc(n)+' <small>(tệp cũ)</small></p>').join('');renderPreview();scrollTo({top:0,behavior:'smooth'})}
function reset(){editing=null;['idea','title','caption','tags'].forEach(id=>$('#'+id).value='');document.querySelectorAll('.channels input').forEach(x=>x.checked=false);if($('#workflow'))$('#workflow').value='Ý tưởng';media=[];$('#media').value='';$('#mediaList').innerHTML='';$('#pTitle').textContent='Chưa có nội dung';$('#pCaption').textContent='Nhập nội dung rồi chọn “Tạo preview”.';$('#pTags').textContent='';$('#pMedia').innerHTML=''}
function esc(s){const d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML}
$('#preview').onclick=renderPreview;
$('#save').onclick=()=>{const d=data(),a=drafts().filter(x=>x.id!==d.id);a.unshift(d);store(a);editing=d.id;renderDrafts();renderPreview()};
$('#newDraft').onclick=reset;
$('#exportDrafts').onclick=()=>{const blob=new Blob([JSON.stringify(drafts(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hcdecor-hub-drafts.json';a.click();URL.revokeObjectURL(a.href)};
$('#drafts').onclick=e=>{const b=e.target.closest('button'),card=e.target.closest('.draft');if(!b||!card)return;const id=Number(card.dataset.id),a=drafts(),d=a.find(x=>x.id===id);if(!d)return;if(b.dataset.act==='edit')load(d);if(b.dataset.act==='copy'){const n={...d,id:Date.now(),title:(d.title||d.idea||'Bản nháp')+' — bản sao',updated:new Date().toLocaleString('vi-VN')};store([n,...a]);renderDrafts()}if(b.dataset.act==='delete'){store(a.filter(x=>x.id!==id));if(editing===id)reset();renderDrafts()}};
renderDrafts();