import {runtimeCapabilities} from "../../lib/data/store";
const systems=[
["Website","/","Public route"],["HUB","/hub","Operations route"],["Leads","/admin/leads","CRM intake"],["Projects","/hub/projects","Project control"],["Media / Drive","/hub/media","Project assets"],["Content","/hub/content","Content workflow"],["Review","/hub/review","Approval gate"],["Web Publish","/hub/publish","Publish control"],["Integrations","/admin/integrations","Connections"],["Health","/admin/health","Runtime status"],["Settings","/admin/settings","Configuration"],["Release Gate","/admin/deploy","WordPress production gate"]];
async function wp(){try{const b=(process.env.HCDECOR_WP_BASE_URL||"").trim();if(!b)return {ok:false,url:null,label:"Chưa cấu hình"};const u=new URL(b);if(!/^https?:$/.test(u.protocol))return {ok:false,url:null,label:"Cấu hình URL không hợp lệ"};const r=await fetch(u.origin+"/wp-json/",{cache:"no-store"});return {ok:r.ok,url:u.origin,label:r.ok?"Đọc được":"Lỗi HTTP "+r.status}}catch{return {ok:false,url:null,label:"Không kết nối"}}}
export default async function Admin(){const cms=await wp(),cap=runtimeCapabilities();
return <main className="admin realAdmin"><div className="adminTop"><div><small>HCDECOR / ADMIN</small><h1>System Control Center</h1><p>Điều khiển các luồng production. Trạng thái cấu hình được tách khỏi kiểm tra kết nối trực tiếp.</p></div><div className="actions"><a className="btn" href="/">Website</a><a className="btn primary" href="/hub">Mở HUB</a></div></div>
<div className="realStatus"><Status n="Website Route" state="AVAILABLE"/><Status n="HUB Route" state="AVAILABLE"/><Status n="CMS Read Probe" state={cms.ok?"LIVE PROBE OK":"ACTION REQUIRED"} detail={cms.label}/><Status n="CMS Write Config" state={cap.cmsWrite?"CONFIGURED":"ACTION REQUIRED"} detail={cap.cmsWrite?"Có credential":"Chưa có quyền ghi"}/><Status n="Drive Write Config" state={cap.driveWrite?"CONFIGURED":"ACTION REQUIRED"} detail={cap.driveWrite?"Đủ cấu hình":"Cần service account + Drive root"}/></div>
<section className="panel"><div className="panelHead"><div><small>OPERATIONS</small><h2>Quản lý theo luồng</h2></div><a className="btn primary" href="/contact">+ Nhận Lead</a></div><div className="adminModules">{systems.map(([n,u,d])=><a href={u} className="adminModule" key={u}><span><b>{n}</b><small>{d}</small></span><strong>Mở →</strong></a>)}</div></section>
<div className="adminGrid"><section className="panel"><small>EXTERNAL SYSTEMS</small><h2>Nguồn production</h2>{cms.url?<External n="WordPress CMS" u={cms.url} state={cms.ok?"Live probe OK":"Check required"}/>:<div className="service"><span className="serviceIcon">EXT</span><b>WordPress CMS</b><strong>Not configured</strong></div>}<External n="GitHub" u="https://github.com/HCDecorAD/HCDecorHUB" state="Source repository"/></section>
<section className="panel"><small>CAPABILITIES</small><h2>Runtime configuration</h2><Capability n="Đọc CMS" ok={cap.cmsRead}/><Capability n="Publish CMS" ok={cap.cmsWrite} reason="Cần WordPress write credential"/><Capability n="Drive Write" ok={cap.driveWrite} reason="Cần service account + Drive root"/><Capability n="Lead Write" ok={cap.leadWrite} reason="Cần Google Sheets provider + credential + sheet"/><Capability n="Project Provision" ok={cap.projectWrite} reason="Cần Sheets + project folder"/></section></div>
<section className="panel"><small>DIAGNOSTICS</small><h2>API kiểm tra</h2><div className="diagLinks"><a href="/api/health">Health API</a><a href="/api/cms/status">CMS Status</a><a href="/api/publish/status">Publish Status</a><a href="/api/wp/status">WordPress Status</a><a href="/api/runtime">Runtime Capabilities</a><a href="/api/leads">Lead Storage Status</a><a href="/api/crm/status">CRM Runtime</a><a href="/api/projects/status">Project Provisioning</a></div></section></main>}
function Status({n,state,detail}){const good=state==="AVAILABLE"||state==="CONNECTED"||state==="CONFIGURED"||state==="LIVE PROBE OK";return <div className={"realStat "+(good?"good":"warn")}><i/><span>{n}</span><b>{state}</b>{detail&&<small>{detail}</small>}</div>}
function External({n,u,state}){return <a className="service" href={u} target="_blank" rel="noreferrer"><span className="serviceIcon">EXT</span><b>{n}</b><strong>{state} →</strong></a>}
function Capability({n,ok,reason}){return <div className="capRow"><span><b>{n}</b>{!ok&&<small>{reason}</small>}</span><strong className={ok?"capOn":"capOff"}>{ok?"CONFIGURED":"DISABLED"}</strong></div>}
