<?php
if(!defined('ABSPATH')) exit;
function hcdecor_conn_get(){ $v=get_option('hcdecor_connections',[]);return is_array($v)?$v:[];}
function hcdecor_conn_safe($x){unset($x['secret'],$x['token'],$x['client_secret'],$x['password']);return $x;}
function hcdecor_conn_status($x){if(empty($x['enabled']))return 'disabled';if(empty($x['endpoint']))return 'action_required';return !empty($x['last_ok'])?'connected':'configured';}
add_action('admin_post_hcdecor_conn_save',function(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('hcdecor_conn_save');$all=hcdecor_conn_get();$id=sanitize_key($_POST['id']??'');if(!$id)$id='conn_'.wp_generate_password(8,false,false);$old=$all[$id]??[];$secret=trim((string)wp_unslash($_POST['secret']??''));$all[$id]=['name'=>sanitize_text_field(wp_unslash($_POST['name']??'')),'provider'=>sanitize_key($_POST['provider']??''),'endpoint'=>esc_url_raw($_POST['endpoint']??''),'account'=>sanitize_text_field(wp_unslash($_POST['account']??'')),'secret'=>$secret!==''?$secret:($old['secret']??''),'enabled'=>!empty($_POST['enabled']),'last_ok'=>$old['last_ok']??'','last_error'=>$old['last_error']??''];update_option('hcdecor_connections',$all,false);wp_safe_redirect(admin_url('admin.php?page=hcdecor-connections'));exit;});
add_action('admin_post_hcdecor_conn_test',function(){if(!current_user_can('manage_options'))wp_die('Forbidden');$id=sanitize_key($_GET['id']??'');check_admin_referer('hcdecor_conn_test_'.$id);$all=hcdecor_conn_get();if(isset($all[$id])){$x=$all[$id];$url=$x['endpoint'];if($url){$res=wp_remote_get($url,['timeout'=>10,'redirection'=>2,'user-agent'=>'HCDecor-HUB/1.0']);if(is_wp_error($res)){$all[$id]['last_error']=$res->get_error_message();}else{$code=wp_remote_retrieve_response_code($res);if($code>=200&&$code<500){$all[$id]['last_ok']=current_time('mysql');$all[$id]['last_error']='';}else $all[$id]['last_error']='HTTP '.$code;}}update_option('hcdecor_connections',$all,false);}wp_safe_redirect(admin_url('admin.php?page=hcdecor-connections'));exit;});
add_action('admin_menu',function(){add_submenu_page('hcdecor-hub','Connection Center','Connections','manage_options','hcdecor-connections','hcdecor_conn_page',4);},29);
function hcdecor_conn_page(){if(!current_user_can('manage_options'))return;$all=hcdecor_conn_get();?><div class="wrap"><h1>HCDecor HUB · Connection Center</h1><p>Secrets lưu phía server, không nằm trong GitHub/manifest.</p><div style="display:grid;grid-template-columns:380px 1fr;gap:14px"><section style="background:#fff;padding:16px;border:1px solid #ddd;border-radius:12px"><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hcdecor_conn_save"><?php wp_nonce_field('hcdecor_conn_save');?><p><input style="width:100%" name="name" placeholder="Tên kết nối"></p><p><select style="width:100%" name="provider"><?php foreach(['wordpress','facebook','tiktok','youtube','zalo','openai','google_drive','webhook'] as $p):?><option value="<?php echo $p;?>"><?php echo esc_html(strtoupper($p));?></option><?php endforeach;?></select></p><p><input style="width:100%" type="url" name="endpoint" placeholder="API / Site endpoint"></p><p><input style="width:100%" name="account" placeholder="Account / Client ID / Username"></p><p><input style="width:100%" type="password" name="secret" autocomplete="new-password" placeholder="Token / App password / API key"></p><label><input type="checkbox" name="enabled" checked> Enabled</label><p><button class="button button-primary">Save Connection</button></p></form></section><section><table class="widefat striped"><thead><tr><th>Connection</th><th>Provider</th><th>Status</th><th>Last OK</th><th>Error</th><th></th></tr></thead><tbody><?php foreach($all as $id=>$x):$st=hcdecor_conn_status($x);?><tr><td><?php echo esc_html($x['name']);?></td><td><?php echo esc_html($x['provider']);?></td><td><strong><?php echo esc_html($st);?></strong></td><td><?php echo esc_html($x['last_ok']);?></td><td><?php echo esc_html($x['last_error']);?></td><td><a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=hcdecor_conn_test&id='.$id),'hcdecor_conn_test_'.$id));?>">Test</a></td></tr><?php endforeach;?></tbody></table></section></div></div><?php}
add_action('rest_api_init',function(){register_rest_route('hcdecor/v1','/connections',['methods'=>'GET','permission_callback'=>'hcdecor_ops_bridge_auth','callback'=>function(){$o=[];foreach(hcdecor_conn_get() as $id=>$x){$o[$id]=hcdecor_conn_safe($x);$o[$id]['status']=hcdecor_conn_status($x);}return rest_ensure_response($o);}]);});
