<?php
if(!defined('ABSPATH')) exit;
function hcdecor_full_calendar_items(){ $ids=get_posts(['post_type'=>'hc_automation_task','post_status'=>'publish','numberposts'=>200,'fields'=>'ids','orderby'=>'date','order'=>'DESC']);$out=[];foreach($ids as $id)$out[]=['id'=>$id,'title'=>get_the_title($id),'status'=>(string)get_post_meta($id,'hc_auto_status',true),'type'=>(string)get_post_meta($id,'hc_auto_type',true),'date'=>get_post_field('post_date',$id)];return $out;}
function hcdecor_full_audit($event,$data=[]){$v=get_option('hcdecor_audit_log',[]);if(!is_array($v))$v=[];$v[]=['at'=>current_time('mysql'),'user'=>get_current_user_id(),'event'=>sanitize_key($event),'data'=>$data];if(count($v)>300)$v=array_slice($v,-300);update_option('hcdecor_audit_log',$v,false);}
add_action('admin_post_hcdecor_full_webhook_save',function(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('hcdecor_full_webhook_save');$v=get_option('hcdecor_integrations',[]);if(!is_array($v))$v=[];$id='hook_'.wp_generate_password(8,false,false);$v[$id]=['name'=>sanitize_text_field($_POST['name']??''),'endpoint'=>esc_url_raw($_POST['endpoint']??''),'event'=>sanitize_key($_POST['event']??''),'enabled'=>!empty($_POST['enabled'])];update_option('hcdecor_integrations',$v,false);hcdecor_full_audit('integration_saved',['id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=hcdecor-full'));exit;});
add_action('admin_menu',function(){add_submenu_page('hcdecor-hub','HUB Full Operations','Full Operations','edit_posts','hcdecor-full','hcdecor_full_page',8);},32);
function hcdecor_full_page(){if(!current_user_can('edit_posts'))return;$cal=hcdecor_full_calendar_items();$hooks=get_option('hcdecor_integrations',[]);if(!is_array($hooks))$hooks=[];$audit=get_option('hcdecor_audit_log',[]);if(!is_array($audit))$audit=[];$leads=get_posts(['post_type'=>'hc_lead','post_status'=>'publish','numberposts'=>100,'fields'=>'ids']);$won=0;foreach($leads as $id)if(get_post_meta($id,'hc_status',true)==='won')$won++;$rate=count($leads)?round($won/count($leads)*100,1):0;?>
<div class="wrap hcf"><style>.hcf{max-width:1500px}.hcf-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.hcf-card{background:#fff;border:1px solid #ddd;border-radius:14px;padding:16px}.hcf-wide{grid-column:1/-1}.hcf input,.hcf select{width:100%;margin:5px 0 9px}.hcf label input{width:auto}.hcf-mod{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.hcf-mod div{padding:12px;border:1px solid #ddd;border-radius:10px}@media(max-width:900px){.hcf-grid,.hcf-mod{grid-template-columns:1fr}}</style><h1>HCDecor HUB · Full Operations</h1><div class="hcf-mod"><?php foreach(['Multi-Web','Social','AI Agent','Workflow','Inbox/CRM','Calendar','Integrations','Audit','Funnel','Reports'] as $x):?><div><strong><?php echo esc_html($x);?></strong><br>ACTIVE FOUNDATION</div><?php endforeach;?></div><div class="hcf-grid" style="margin-top:12px">
<section class="hcf-card"><h2>Content Calendar</h2><table class="widefat striped"><thead><tr><th>Ngày</th><th>Task</th><th>Loại</th><th>Status</th></tr></thead><tbody><?php foreach(array_slice($cal,0,20) as $x):?><tr><td><?php echo esc_html($x['date']);?></td><td><?php echo esc_html($x['title']);?></td><td><?php echo esc_html($x['type']);?></td><td><?php echo esc_html($x['status']);?></td></tr><?php endforeach;?></tbody></table></section>
<section class="hcf-card"><h2>Integration / Webhook Center</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hcdecor_full_webhook_save"><?php wp_nonce_field('hcdecor_full_webhook_save');?><input name="name" placeholder="Tên integration"><input type="url" name="endpoint" placeholder="Webhook endpoint"><select name="event"><option value="project_created">Project created</option><option value="content_approved">Content approved</option><option value="lead_created">Lead created</option><option value="publish_done">Publish done</option></select><label><input type="checkbox" name="enabled" checked> Enabled</label><p><button class="button button-primary">Lưu Integration</button></p></form><p>Configured: <strong><?php echo count($hooks);?></strong></p></section>
<section class="hcf-card"><h2>Conversion Funnel</h2><p>Leads: <strong><?php echo count($leads);?></strong></p><p>Won: <strong><?php echo $won;?></strong></p><p>Lead → Won: <strong><?php echo esc_html($rate);?>%</strong></p><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=hcdecor-pipeline'));?>">CRM Pipeline</a></section>
<section class="hcf-card"><h2>AI Agent & Human Review</h2><p>AI Workspace xử lý content; Review/Approval giữ quyền xuất bản quan trọng ở người vận hành.</p><a class="button button-primary" href="<?php echo esc_url(admin_url('admin.php?page=hcdecor-ai-workspace'));?>">AI Workspace</a> <a class="button" href="<?php echo esc_url(admin_url('admin.php?page=hcdecor-content-operations'));?>">Review</a></section>
<section class="hcf-card hcf-wide"><h2>Audit / Error Monitor / Reports</h2><table class="widefat striped"><thead><tr><th>Thời gian</th><th>Event</th><th>User</th></tr></thead><tbody><?php foreach(array_reverse(array_slice($audit,-30)) as $x):?><tr><td><?php echo esc_html($x['at']);?></td><td><?php echo esc_html($x['event']);?></td><td><?php echo (int)$x['user'];?></td></tr><?php endforeach;?></tbody></table><p><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=hcdecor-automation'));?>">Automation Errors & Reports</a></p></section></div></div><?php}
add_action('rest_api_init',function(){register_rest_route('hcdecor/v1','/full/status',['methods'=>'GET','permission_callback'=>'hcdecor_ops_bridge_auth','callback'=>function(){return rest_ensure_response(['calendar'=>count(hcdecor_full_calendar_items()),'integrations'=>count((array)get_option('hcdecor_integrations',[])),'audit'=>count((array)get_option('hcdecor_audit_log',[])),'websites'=>function_exists('hcdecor_suite_sites')?count(hcdecor_suite_sites()):0,'workflows'=>function_exists('hcdecor_ops_flows')?count(hcdecor_ops_flows()):0]);}]);});
