<?php
if(!defined('ABSPATH')) exit;
function hcdecor_runtime_jobs(){ $v=get_option('hcdecor_runtime_jobs',[]);return is_array($v)?$v:[];}
function hcdecor_runtime_enqueue($type,$target,$payload=[],$when=''){ $v=hcdecor_runtime_jobs();$id='job_'.wp_generate_password(10,false,false);$v[$id]=['type'=>sanitize_key($type),'target'=>sanitize_key($target),'payload'=>$payload,'status'=>'queued','attempts'=>0,'scheduled'=>$when?:current_time('mysql'),'created'=>current_time('mysql'),'last_error'=>'','result'=>[]];update_option('hcdecor_runtime_jobs',$v,false);if(!wp_next_scheduled('hcdecor_runtime_tick'))wp_schedule_single_event(time()+5,'hcdecor_runtime_tick');return $id;}
function hcdecor_runtime_execute($id,$job){$conns=function_exists('hcdecor_conn_get')?hcdecor_conn_get():[];$conn=$conns[$job['target']]??null;if(!$conn||empty($conn['enabled'])||empty($conn['endpoint']))return new WP_Error('connection','Connection unavailable');$body=$job['payload'];$args=['timeout'=>20,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode($body)];if(!empty($conn['secret']))$args['headers']['Authorization']='Bearer '.$conn['secret'];$res=wp_remote_post($conn['endpoint'],$args);if(is_wp_error($res))return $res;$code=wp_remote_retrieve_response_code($res);if($code<200||$code>=300)return new WP_Error('remote_http','HTTP '.$code);return ['http'=>$code,'body'=>substr((string)wp_remote_retrieve_body($res),0,2000)];}
add_action('hcdecor_runtime_tick',function(){$v=hcdecor_runtime_jobs();$changed=false;$now=current_time('timestamp');foreach($v as $id=>$j){if($j['status']!=='queued')continue;if(strtotime($j['scheduled'])>$now)continue;$v[$id]['status']='running';$v[$id]['attempts']++;update_option('hcdecor_runtime_jobs',$v,false);$res=hcdecor_runtime_execute($id,$v[$id]);if(is_wp_error($res)){$v[$id]['last_error']=$res->get_error_message();$v[$id]['status']=$v[$id]['attempts']<3?'queued':'failed';$v[$id]['scheduled']=date('Y-m-d H:i:s',$now+min(900,60*pow(2,$v[$id]['attempts'])));}else{$v[$id]['status']='done';$v[$id]['result']=$res;} $changed=true;}if($changed)update_option('hcdecor_runtime_jobs',$v,false);foreach($v as $j)if($j['status']==='queued'){wp_schedule_single_event(time()+60,'hcdecor_runtime_tick');break;}});
add_action('admin_post_hcdecor_runtime_publish',function(){if(!current_user_can('edit_posts'))wp_die('Forbidden');check_admin_referer('hcdecor_runtime_publish');$pid=(int)($_POST['project_id']??0);$targets=array_map('sanitize_key',(array)($_POST['targets']??[]));$p=get_post($pid);if($p&&$p->post_type==='hc_project'){foreach($targets as $t)hcdecor_runtime_enqueue('publish',$t,['project_id'=>$pid,'title'=>get_the_title($p),'content'=>wp_strip_all_tags($p->post_content),'content_pack'=>get_post_meta($pid,'hc_content_pack',true)],sanitize_text_field($_POST['scheduled']??''));}wp_safe_redirect(admin_url('admin.php?page=hcdecor-runtime'));exit;});
add_action('admin_menu',function(){add_submenu_page('hcdecor-hub','Publish Runtime','Publish Runtime','edit_posts','hcdecor-runtime','hcdecor_runtime_page',6);},30);
function hcdecor_runtime_page(){$jobs=hcdecor_runtime_jobs();$conns=function_exists('hcdecor_conn_get')?hcdecor_conn_get():[];$projects=get_posts(['post_type'=>'hc_project','post_status'=>'publish','numberposts'=>50]);?><div class="wrap"><h1>HCDecor HUB · End-to-End Publish Runtime</h1><div style="background:#fff;border:1px solid #ddd;border-radius:12px;padding:16px;max-width:900px"><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hcdecor_runtime_publish"><?php wp_nonce_field('hcdecor_runtime_publish');?><p><select name="project_id" style="width:100%"><?php foreach($projects as $p):?><option value="<?php echo $p->ID;?>"><?php echo esc_html($p->post_title);?></option><?php endforeach;?></select></p><p><?php foreach($conns as $id=>$x):if(empty($x['enabled']))continue;?><label style="display:block"><input type="checkbox" name="targets[]" value="<?php echo esc_attr($id);?>"> <?php echo esc_html($x['name'].' · '.$x['provider']);?></label><?php endforeach;?></p><p><input type="datetime-local" name="scheduled"> <button class="button button-primary">Queue Publish</button></p></form></div><h2>Execution Queue</h2><table class="widefat striped"><thead><tr><th>Job</th><th>Type</th><th>Target</th><th>Status</th><th>Attempts</th><th>Schedule</th><th>Error</th></tr></thead><tbody><?php foreach(array_reverse($jobs,true) as $id=>$j):?><tr><td><?php echo esc_html($id);?></td><td><?php echo esc_html($j['type']);?></td><td><?php echo esc_html($j['target']);?></td><td><?php echo esc_html($j['status']);?></td><td><?php echo (int)$j['attempts'];?></td><td><?php echo esc_html($j['scheduled']);?></td><td><?php echo esc_html($j['last_error']);?></td></tr><?php endforeach;?></tbody></table></div><?php}
add_action('rest_api_init',function(){register_rest_route('hcdecor/v1','/runtime/jobs',['methods'=>'GET','permission_callback'=>'hcdecor_ops_bridge_auth','callback'=>function(){return rest_ensure_response(hcdecor_runtime_jobs());}]);});
