<?php
if(!defined('ABSPATH')) exit;
function hcdecor_ops_flows(){ $v=get_option('hcdecor_ops_flows',[]);return is_array($v)?$v:[];}
function hcdecor_ops_inbox(){ $v=get_option('hcdecor_ops_inbox',[]);return is_array($v)?$v:[];}
add_action('admin_post_hcdecor_ops_flow_save',function(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('hcdecor_ops_flow_save');$v=hcdecor_ops_flows();$id='flow_'.wp_generate_password(8,false,false);$v[$id]=['name'=>sanitize_text_field($_POST['name']??''),'trigger'=>sanitize_key($_POST['trigger']??''),'filter'=>sanitize_text_field($_POST['filter']??''),'action'=>sanitize_key($_POST['flow_action']??''),'enabled'=>!empty($_POST['enabled'])];update_option('hcdecor_ops_flows',$v,false);wp_safe_redirect(admin_url('admin.php?page=hcdecor-ops'));exit;});
add_action('admin_post_hcdecor_ops_inbox_add',function(){if(!current_user_can('edit_posts'))wp_die('Forbidden');check_admin_referer('hcdecor_ops_inbox_add');$v=hcdecor_ops_inbox();$id='msg_'.wp_generate_password(8,false,false);$v[$id]=['name'=>sanitize_text_field(wp_unslash($_POST['name']??'')),'source'=>sanitize_key($_POST['source']??'manual'),'contact'=>sanitize_text_field(wp_unslash($_POST['contact']??'')),'message'=>sanitize_textarea_field(wp_unslash($_POST['message']??'')),'status'=>'new','at'=>current_time('mysql')];update_option('hcdecor_ops_inbox',$v,false);wp_safe_redirect(admin_url('admin.php?page=hcdecor-ops'));exit;});
add_action('admin_post_hcdecor_ops_to_lead',function(){if(!current_user_can('edit_posts'))wp_die('Forbidden');$id=sanitize_key($_GET['id']??'');check_admin_referer('hcdecor_ops_to_lead_'.$id);$v=hcdecor_ops_inbox();if(isset($v[$id])){$x=$v[$id];$lead=wp_insert_post(['post_type'=>'hc_lead','post_status'=>'publish','post_title'=>$x['name']?:'Lead · '.$x['source'],'post_content'=>$x['message']]);if($lead&&!is_wp_error($lead)){update_post_meta($lead,'hc_status','new');update_post_meta($lead,'hc_source',$x['source']);update_post_meta($lead,'hc_phone',$x['contact']);$v[$id]['status']='lead';update_option('hcdecor_ops_inbox',$v,false);}}wp_safe_redirect(admin_url('admin.php?page=hcdecor-ops'));exit;});
add_action('admin_menu',function(){add_submenu_page('hcdecor-hub','Workflow & CRM','Workflow & CRM','edit_posts','hcdecor-ops','hcdecor_ops_page',7);},31);
function hcdecor_ops_page(){if(!current_user_can('edit_posts'))return;$flows=hcdecor_ops_flows();$inbox=hcdecor_ops_inbox();$leads=(int)(wp_count_posts('hc_lead')->publish??0);?>
<div class="wrap hcops"><style>.hcops{max-width:1450px}.hcops-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.hcops-card{background:#fff;border:1px solid #ddd;border-radius:14px;padding:16px}.hcops input,.hcops select,.hcops textarea{width:100%;margin:5px 0 9px}.hcops label input{width:auto}.hcops-flow{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.hcops-node{padding:8px 11px;border:1px solid #dcdcde;border-radius:10px;background:#f6f7f7}@media(max-width:900px){.hcops-grid{grid-template-columns:1fr}}</style><h1>Workflow & CRM</h1><p>Visual Workflow foundation · Unified Inbox · Lead Pipeline</p><div class="hcops-grid">
<section class="hcops-card"><h2>Visual Workflow Builder</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hcdecor_ops_flow_save"><?php wp_nonce_field('hcdecor_ops_flow_save');?><input name="name" placeholder="Tên workflow"><select name="trigger"><option value="project_created">Project created</option><option value="content_approved">Content approved</option><option value="lead_created">Lead created</option><option value="schedule">Schedule</option></select><input name="filter" placeholder="Filter / điều kiện"><select name="flow_action"><option value="ai_content">AI Content</option><option value="web_publish">Web Publish</option><option value="social_publish">Social Publish</option><option value="notify">Notify</option></select><label><input type="checkbox" name="enabled" checked> Enabled</label><p><button class="button button-primary">Lưu Workflow</button></p></form><?php foreach($flows as $f):?><div class="hcops-flow"><span class="hcops-node"><?php echo esc_html($f['trigger']);?></span>→<span class="hcops-node"><?php echo esc_html($f['filter']?:'No filter');?></span>→<span class="hcops-node"><?php echo esc_html($f['action']);?></span></div><?php endforeach;?></section>
<section class="hcops-card"><h2>Unified Inbox</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hcdecor_ops_inbox_add"><?php wp_nonce_field('hcdecor_ops_inbox_add');?><input name="name" placeholder="Khách hàng"><select name="source"><option value="website">Website</option><option value="facebook">Facebook</option><option value="tiktok">TikTok</option><option value="zalo">Zalo</option><option value="manual">Manual</option></select><input name="contact" placeholder="Điện thoại / contact"><textarea name="message" rows="3" placeholder="Nội dung"></textarea><button class="button">Thêm Inbox</button></form><hr><?php foreach(array_reverse($inbox,true) as $id=>$x):?><p><strong><?php echo esc_html($x['name']);?></strong> · <?php echo esc_html(strtoupper($x['source']));?> · <?php echo esc_html($x['status']);?> <?php if($x['status']==='new'):?><a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=hcdecor_ops_to_lead&id='.$id),'hcdecor_ops_to_lead_'.$id));?>">→ Lead</a><?php endif;?></p><?php endforeach;?></section>
<section class="hcops-card"><h2>CRM / Lead Pipeline</h2><p><strong><?php echo $leads;?></strong> leads hiện có.</p><p><a class="button button-primary" href="<?php echo esc_url(admin_url('admin.php?page=hcdecor-pipeline'));?>">Mở Pipeline</a></p></section>
<section class="hcops-card"><h2>Automation Bridge</h2><p>Workflow definitions được lưu tập trung để kết nối Automation HUB, AI Agent, Website và Social adapters.</p><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=hcdecor-automation'));?>">Automation HUB</a></section></div></div><?php}
