const ENGINE=process.env.HC_SHOP_ENGINE_URL||"https://hc-shop-engine.huycuongonline.workers.dev";
const STORE=process.env.HC_SHOP_STORE_ID||"store_amo";
const ALLOWED=new Set(["stores","products","variants","brands","categories","product-drafts","channels","listings","warehouses","locations","inventory","stock-movements","reservations","orders","import-jobs"]);
const WRITE_ALLOWED=new Set(["product-draft-create","product-draft-state","import-job-create","import-job-stage","import-job-dry-run","listing-create","listing-state","listing-activate","order-state"]);
function credential(){return process.env.HC_SHOP_ADMIN_TOKEN||""}
async function call(path,init={}){const token=credential();if(!token)return {ok:false,status:503,error:"credential_not_configured",items:[]};try{let binding=null;try{binding=(await import("@opennextjs/cloudflare")).getCloudflareContext().env.HC_SHOP_ENGINE}catch{};const target=binding||{fetch};const url=binding?("https://hc-shop-engine.internal"+path):(ENGINE+path);const r=await target.fetch(url,{...init,headers:{"x-store-id":STORE,authorization:"Bearer "+token,"content-type":"application/json",...(init.headers||{})},cache:"no-store"});const data=await r.json().catch(()=>({}));return {ok:r.ok,status:r.status,error:r.ok?null:(data.error||"upstream_error"),items:Array.isArray(data.items)?data.items:[],data}}catch{return {ok:false,status:503,error:"engine_unreachable",items:[]}}}
export function commerceAdminCapability(){return {configured:Boolean(credential()),mode:"server_only",production_write:false,draft_write:true,commit_write:false}}
export async function commerceAdminRead(resource,id=""){if(!ALLOWED.has(resource))return {ok:false,status:400,error:"resource_not_allowed",items:[]};const suffix=id&&resource==="import-jobs"?"/"+encodeURIComponent(id):"";return call("/api/v1/"+resource+suffix)}
export async function commerceAdminDraft(action,payload={}){if(!WRITE_ALLOWED.has(action))return {ok:false,status:423,error:"write_locked"};if(action==="product-draft-create")return call("/api/v1/product-drafts",{method:"POST",body:JSON.stringify(payload)});if(action==="product-draft-state"){if(!payload.id||!["review","draft","rejected"].includes(payload.to))return {ok:false,status:400,error:"invalid_draft_transition"};return call("/api/v1/product-drafts/"+encodeURIComponent(payload.id)+"/state",{method:"POST",body:JSON.stringify({to:payload.to})})}if(action==="listing-create")return call("/api/v1/listings",{method:"POST",body:JSON.stringify(payload)});if(action==="listing-activate"){if(!payload.id)return {ok:false,status:400,error:"id_required"};return call("/api/v1/listings/"+encodeURIComponent(payload.id)+"/activate",{method:"POST",body:"{}"})}if(action==="order-state"){if(!payload.id||!["confirmed","packing","shipping","completed","cancelled","returned"].includes(payload.to))return {ok:false,status:400,error:"invalid_order_transition"};return call("/api/orders/"+encodeURIComponent(payload.id)+"/status",{method:"POST",body:JSON.stringify({status:payload.to,note:payload.note||"HCDecor HUB"})})}if(action==="listing-state"){if(!payload.id||!["review","draft","approved"].includes(payload.to))return {ok:false,status:400,error:"invalid_listing_transition"};return call("/api/v1/listings/"+encodeURIComponent(payload.id)+"/state",{method:"POST",body:JSON.stringify({to:payload.to})})}if(action==="import-job-create")return call("/api/v1/import-jobs",{method:"POST",body:JSON.stringify(payload)});if(!payload.id)return {ok:false,status:400,error:"id_required"};const suffix=action==="import-job-stage"?"stage":"dry-run";const body=action==="import-job-stage"?payload:{};return call("/api/v1/import-jobs/"+encodeURIComponent(payload.id)+"/"+suffix,{method:"POST",body:JSON.stringify(body)})}
