import crypto from "node:crypto";
import {businessRuntime} from "./config";
import {appendBusiness,deleteBusiness,getBusiness,listBusiness,newBusinessId,updateBusiness} from "./google";
import {requireSameOriginMutation} from "../request-guard";

const clean=v=>typeof v==="string"?v.trim():"";
function authorized(req){const expected=(process.env.HCDECOR_BUSINESS_API_TOKEN||process.env.HCDECOR_PROJECT_API_TOKEN||"").trim(),header=req.headers.get("authorization")||"";if(expected.length<32||!header.startsWith("Bearer "))return false;const supplied=header.slice(7);if(supplied.length!==expected.length)return false;return crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected))}
function freshApproval(d){if(d.confirmExternalWrite!==true)return false;const by=clean(d.approvedBy),raw=clean(d.approvedAt);const at=Date.parse(raw);return Boolean(by)&&Number.isFinite(at)&&at>=Date.now()-15*60*1000&&at<=Date.now()+5*60*1000}
async function body(req){try{return await req.json()}catch{return null}}
function sanitize(d){return {name:clean(d.name).slice(0,200),ref_id:clean(d.ref_id).slice(0,160),status:clean(d.status).slice(0,80),amount:clean(d.amount).slice(0,80),contact:clean(d.contact).slice(0,200),notes:clean(d.notes).slice(0,5000)}}
export function businessHandlers(resource){
 return {
  async GET(req){const r=businessRuntime(),u=new URL(req.url),id=clean(u.searchParams.get("id"));if(!r.configured||!r.credentials)return Response.json({service:"ok",resource,configured:r.configured,credentials:r.credentials,items:[],liveHealth:"not_configured",production_write:false});try{if(id){const item=await getBusiness(resource,id);return Response.json({service:"ok",resource,configured:true,credentials:true,item,production_write:false})}const items=await listBusiness(resource,Number(u.searchParams.get("limit"))||100);return Response.json({service:"ok",resource,configured:true,credentials:true,items,count:items.length,production_write:false})}catch{return Response.json({service:"ok",resource,configured:true,credentials:true,items:[],liveHealth:"degraded",production_write:false},{status:503})}},
  async POST(req){const blocked=requireSameOriginMutation(req);if(blocked)return blocked;const r=businessRuntime();if(!r.writeEnabled)return Response.json({ok:false,error:"business_runtime_not_configured"},{status:503});if(!authorized(req))return Response.json({ok:false,error:"unauthorized"},{status:401});const d=await body(req);if(!d)return Response.json({ok:false,error:"invalid_json"},{status:400});if(!freshApproval(d))return Response.json({ok:false,error:"fresh_external_write_approval_required"},{status:403});const x=sanitize(d);if(!x.name)return Response.json({ok:false,error:"name_required"},{status:400});x.id=newBusinessId(resource);x.created_at=new Date().toISOString();await appendBusiness(resource,x);return Response.json({ok:true,item:x},{status:201})},
  async PATCH(req){const blocked=requireSameOriginMutation(req);if(blocked)return blocked;const r=businessRuntime();if(!r.writeEnabled)return Response.json({ok:false,error:"business_runtime_not_configured"},{status:503});if(!authorized(req))return Response.json({ok:false,error:"unauthorized"},{status:401});const d=await body(req);if(!d)return Response.json({ok:false,error:"invalid_json"},{status:400});if(!freshApproval(d))return Response.json({ok:false,error:"fresh_external_write_approval_required"},{status:403});const id=clean(d.id);if(!id)return Response.json({ok:false,error:"id_required"},{status:400});const item=await updateBusiness(resource,id,sanitize(d));return item?Response.json({ok:true,item}):Response.json({ok:false,error:"not_found"},{status:404})},
  async DELETE(req){const blocked=requireSameOriginMutation(req);if(blocked)return blocked;const r=businessRuntime();if(!r.writeEnabled)return Response.json({ok:false,error:"business_runtime_not_configured"},{status:503});if(!authorized(req))return Response.json({ok:false,error:"unauthorized"},{status:401});const d=await body(req);if(!d)return Response.json({ok:false,error:"invalid_json"},{status:400});if(!freshApproval(d))return Response.json({ok:false,error:"fresh_external_write_approval_required"},{status:403});const id=clean(d.id);if(!id)return Response.json({ok:false,error:"id_required"},{status:400});const item=await deleteBusiness(resource,id);return item?Response.json({ok:true,item}):Response.json({ok:false,error:"not_found"},{status:404})}
 };
}
