import crypto from "node:crypto";
import {readFileSync} from "node:fs";
import {BUSINESS,businessRuntime} from "./config";

const enc=v=>Buffer.from(v).toString("base64url");
function credentials(){let raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;const p=(process.env.GOOGLE_APPLICATION_CREDENTIALS||"").trim();if(!raw&&p)try{raw=readFileSync(p,"utf8")}catch{}if(!raw)throw new Error("google_credentials_missing");return JSON.parse(raw)}
async function token(){const c=credentials(),now=Math.floor(Date.now()/1000);const head=enc(JSON.stringify({alg:"RS256",typ:"JWT"}));const body=enc(JSON.stringify({iss:c.client_email,scope:"https://www.googleapis.com/auth/spreadsheets",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const input=head+"."+body;const sign=crypto.createSign("RSA-SHA256");sign.update(input);sign.end();const assertion=input+"."+sign.sign(c.private_key).toString("base64url");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}),cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("google_auth_failed");return (await r.json()).access_token}
async function gs(url,opt={}){const t=await token();const r=await fetch(url,{...opt,headers:{authorization:"Bearer "+t,"content-type":"application/json",...(opt.headers||{})},cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("google_api_"+r.status);return r.status===204?null:r.json()}
function tab(resource){const x=BUSINESS.tabs[resource];if(!x)throw new Error("invalid_business_resource");return x}
function rowToObject(row=[]){return {id:String(row[0]||""),created_at:String(row[1]||""),name:String(row[2]||""),ref_id:String(row[3]||""),status:String(row[4]||""),amount:String(row[5]||""),contact:String(row[6]||""),notes:String(row[7]||"")}}
function objectToRow(x){return [x.id||"",x.created_at||"",x.name||"",x.ref_id||"",x.status||"",x.amount||"",x.contact||"",x.notes||""]}
export async function listBusiness(resource,limit=100){if(!businessRuntime().configured)return [];const t=tab(resource),max=Math.max(1,Math.min(Number(limit)||100,500));const d=await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(t)}!A:H?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];return rows.slice(1).map(rowToObject).filter(x=>x.id).slice(-max).reverse()}
export async function getBusiness(resource,id){const rows=await listBusiness(resource,500);return rows.find(x=>x.id===String(id||"").trim())||null}
export async function appendBusiness(resource,x){if(!businessRuntime().writeEnabled)throw new Error("business_write_not_configured");const t=tab(resource);return gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(t)}!A:H:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values:[objectToRow(x)]})})}
export async function updateBusiness(resource,id,patch){if(!businessRuntime().writeEnabled)throw new Error("business_write_not_configured");const t=tab(resource);const d=await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(t)}!A:H?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];const i=rows.findIndex((r,n)=>n>0&&String(r?.[0]||"").trim()===id);if(i<1)return null;const next={...rowToObject(rows[i]),...patch,id};await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(t)}!A${i+1}:H${i+1}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values:[objectToRow(next)]})});return next}
export async function deleteBusiness(resource,id){if(!businessRuntime().writeEnabled)throw new Error("business_write_not_configured");const t=tab(resource);const meta=await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}?fields=sheets.properties`);const props=(meta?.sheets||[]).map(x=>x.properties).find(x=>x?.title===t);if(!props)return null;const d=await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(t)}!A:H?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];const i=rows.findIndex((r,n)=>n>0&&String(r?.[0]||"").trim()===id);if(i<1)return null;const current=rowToObject(rows[i]);await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:[{deleteDimension:{range:{sheetId:props.sheetId,dimension:"ROWS",startIndex:i,endIndex:i+1}}}]})});return current}
export function newBusinessId(resource){return resource.slice(0,3).toUpperCase()+"-"+Date.now().toString(36).toUpperCase()+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}

export async function ensureBusinessSchema(){if(!businessRuntime().writeEnabled)throw new Error("business_write_not_configured");const meta=await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}?fields=sheets.properties`);const existing=new Set((meta?.sheets||[]).map(x=>x?.properties?.title).filter(Boolean));const missing=Object.values(BUSINESS.tabs).filter(t=>!existing.has(t));if(missing.length){await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:missing.map(title=>({addSheet:{properties:{title}}}))})})}const headers=["ID","CreatedAt","Name","RefID","Status","Amount","Contact","Notes"];const initialized=[];for(const title of Object.values(BUSINESS.tabs)){const d=await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(title)}!A1:H1?majorDimension=ROWS`);const row=Array.isArray(d?.values)&&Array.isArray(d.values[0])?d.values[0]:[];if(row.length===0){await gs(`https://sheets.googleapis.com/v4/spreadsheets/${BUSINESS.sheetId}/values/${encodeURIComponent(title)}!A1:H1?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values:[headers]})});initialized.push(title)}}return {ok:true,created_tabs:missing,initialized_headers:initialized,tabs:Object.values(BUSINESS.tabs)}}
