import crypto from "node:crypto";
import {readFileSync} from "node:fs";
import {CRM,crmRuntime,googleCredentialsConfigured} from "./config";
import {parseProjectRow} from "./project-row";
const enc=v=>Buffer.from(v).toString("base64url");
function credentials(){let raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;const p=(process.env.GOOGLE_APPLICATION_CREDENTIALS||"").trim();if(!raw&&p)try{raw=readFileSync(p,"utf8")}catch{}if(!raw)throw new Error("google_credentials_missing");return JSON.parse(raw)}
async function token(){const c=credentials(),now=Math.floor(Date.now()/1000);const head=enc(JSON.stringify({alg:"RS256",typ:"JWT"}));const body=enc(JSON.stringify({iss:c.client_email,scope:"https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const input=head+"."+body;const sign=crypto.createSign("RSA-SHA256");sign.update(input);sign.end();const assertion=input+"."+sign.sign(c.private_key).toString("base64url");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}),cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("google_auth_failed");return (await r.json()).access_token}
async function g(url,opt={}){const t=await token();const r=await fetch(url,{...opt,headers:{authorization:"Bearer "+t,"content-type":"application/json",...(opt.headers||{})},cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("google_api_"+r.status);return r.status===204?null:r.json()}
export async function probeGoogleRuntime(){try{const [sheet,drive]=await Promise.all([g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}?fields=spreadsheetId,properties.title`),g(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(CRM.projectsFolderId)}?fields=id,name,mimeType`)]);return {ok:Boolean(sheet?.spreadsheetId&&drive?.id),sheets:Boolean(sheet?.spreadsheetId),drive:Boolean(drive?.id),credentials_validated:true,production_write:false}}catch{return {ok:false,sheets:false,drive:false,credentials_validated:false,production_write:false}}}
export async function appendLead(x){if(!crmRuntime().writeEnabled)throw new Error("crm_write_not_configured");return g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Leads!A:J:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values:[[x.id,x.createdAt,x.name,x.phone,x.service||"",x.location||"",x.brief,"New","",x.notes||""]]})})}
export async function appendProject(x){if(!crmRuntime().projectProvisionEnabled)throw new Error("project_write_not_configured");return g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values:[[x.projectId,x.createdAt,x.leadId||"",x.client||"",x.service||"",x.location||"",x.status||"Active",x.folderId,x.folderUrl,x.notes||""]]})})}
export async function listProjects(limit=100){const max=Math.max(1,Math.min(Number(limit)||100,500));if(!CRM.sheetId||!googleCredentialsConfigured())return [];const d=await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];return rows.slice(1).filter(Array.isArray).map(row=>parseProjectRow(row,row?.[0])).filter(Boolean).slice(-max).reverse()}
export async function getProjectById(projectId){const id=String(projectId||"").trim().slice(0,120);if(!id||!CRM.sheetId||!googleCredentialsConfigured())return null;const d=await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];const row=rows.find((x,i)=>i>0&&String(x?.[0]||"").trim()===id);return row?parseProjectRow(row,id):null}
export async function deleteDriveFile(fileId){if(!fileId)return;await g(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}`,{method:"DELETE"})}
export async function createProjectFolder(projectId){if(!crmRuntime().projectProvisionEnabled)throw new Error("project_write_not_configured");if(!CRM.projectsFolderId)throw new Error("projects_folder_missing");const d=await g("https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink",{method:"POST",body:JSON.stringify({name:projectId,mimeType:"application/vnd.google-apps.folder",parents:[CRM.projectsFolderId]})});return {...d,folderUrl:`https://drive.google.com/drive/folders/${d.id}`}}
export async function updateProject(projectId,patch={}){if(!crmRuntime().projectProvisionEnabled)throw new Error("project_write_not_configured");const id=String(projectId||"").trim().slice(0,120);if(!id)throw new Error("project_id_required");const d=await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];const i=rows.findIndex((x,n)=>n>0&&String(x?.[0]||"").trim()===id);if(i<1)return null;const current=parseProjectRow(rows[i],id);const next={...current,...patch,project_id:id};const values=[[id,next.created_at||"",next.lead_id||"",next.client||"",next.service||"",next.location||"",next.status||"Active",next.folder_id||"",next.folder_url||"",next.notes||""]];await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A${i+1}:J${i+1}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values})});return parseProjectRow(values[0],id)}
export async function deleteProject(projectId,{deleteFolder=false}={}){if(!crmRuntime().projectProvisionEnabled)throw new Error("project_write_not_configured");const id=String(projectId||"").trim().slice(0,120);if(!id)throw new Error("project_id_required");const d=await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}?fields=sheets.properties`);const props=(d?.sheets||[]).map(x=>x.properties).find(x=>x?.title==="Projects");if(!props)return null;const rowsData=await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J?majorDimension=ROWS`);const rows=Array.isArray(rowsData?.values)?rowsData.values:[];const i=rows.findIndex((x,n)=>n>0&&String(x?.[0]||"").trim()===id);if(i<1)return null;const project=parseProjectRow(rows[i],id);await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:[{deleteDimension:{range:{sheetId:props.sheetId,dimension:"ROWS",startIndex:i,endIndex:i+1}}}]})});if(deleteFolder&&project?.folder_id)await deleteDriveFile(project.folder_id);return project}
export function newLeadId(){return "LEAD-"+Date.now()+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}
export function newProjectId(){const y=new Date().getFullYear();return `HC-${y}-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`}