import crypto from "node:crypto";
import {CRM,crmRuntime} from "./config";
const enc=v=>Buffer.from(v).toString("base64url");
function credentials(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error("google_credentials_missing");return JSON.parse(raw)}
async function token(){const c=credentials(),now=Math.floor(Date.now()/1000);const head=enc(JSON.stringify({alg:"RS256",typ:"JWT"}));const body=enc(JSON.stringify({iss:c.client_email,scope:"https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const input=head+"."+body;const sign=crypto.createSign("RSA-SHA256");sign.update(input);sign.end();const assertion=input+"."+sign.sign(c.private_key).toString("base64url");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}),cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("google_auth_failed");return (await r.json()).access_token}
async function g(url,opt={}){const t=await token();const r=await fetch(url,{...opt,headers:{authorization:"Bearer "+t,"content-type":"application/json",...(opt.headers||{})},cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("google_api_"+r.status);return r.status===204?null:r.json()}
export async function appendLead(x){if(!crmRuntime().writeEnabled)throw new Error("crm_write_not_configured");return g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Leads!A:J:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values:[[x.id,x.createdAt,x.name,x.phone,x.service||"",x.location||"",x.brief,"New","",x.notes||""]]})})}
export async function appendProject(x){return g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values:[[x.projectId,x.createdAt,x.leadId||"",x.client||"",x.service||"",x.location||"",x.status||"Active",x.folderId,x.folderUrl,x.notes||""]]})})}
export async function getProjectById(projectId){const id=String(projectId||"").trim().slice(0,120);if(!id||!CRM.sheetId||!process.env.GOOGLE_SERVICE_ACCOUNT_JSON)return null;const d=await g(`https://sheets.googleapis.com/v4/spreadsheets/${CRM.sheetId}/values/Projects!A:J?majorDimension=ROWS`);const rows=Array.isArray(d?.values)?d.values:[];const row=rows.find((x,i)=>i>0&&String(x?.[0]||"").trim()===id);if(!row)return null;return {project_id:id,created_at:String(row[1]||"").slice(0,64),lead_id:String(row[2]||"").slice(0,200),client:String(row[3]||"").slice(0,200),service:String(row[4]||"").slice(0,120),location:String(row[5]||"").slice(0,500),status:String(row[6]||"").slice(0,80),folder_id:String(row[7]||"").slice(0,256),folder_url:String(row[8]||"").slice(0,1000),notes:String(row[9]||"").slice(0,2000)}}
export async function deleteDriveFile(fileId){if(!fileId)return;await g(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}`,{method:"DELETE"})}
export async function createProjectFolder(projectId){if(!CRM.projectsFolderId)throw new Error("projects_folder_missing");const d=await g("https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink",{method:"POST",body:JSON.stringify({name:projectId,mimeType:"application/vnd.google-apps.folder",parents:[CRM.projectsFolderId]})});return {...d,folderUrl:`https://drive.google.com/drive/folders/${d.id}`}}
export function newLeadId(){return "LEAD-"+Date.now()+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}
export function newProjectId(){const y=new Date().getFullYear();return `HC-${y}-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`}