const nav=["Bảng điều khiển","Projects","Media Manager","AI Providers","Automation HUB","Lịch nội dung","Review Center","Web Publish","Social Accounts","Integrations","Logs & Reports"];
const queue=[["GSC Senior Living","AI Content","Đang xử lý"],["Case study dự án","Website","Sẵn sàng"],["Project Reel","Media","Chờ duyệt"]];
export default async function Home(){
 let cms={read:{ok:false},write:{mode:"demo-readonly"}};
 try{const base=process.env.HCDECOR_WP_BASE_URL;if(base){const r=await fetch(base.replace(/\/$/,"")+"/wp-json/",{cache:"no-store"});cms.read={ok:r.ok,http:r.status};}}catch{}
 return <main className="shell"><aside><div className="brand"><span>HC</span><div>HCDecor HUB<small>AGENT · V2</small></div></div><div className="workspace">Operations Center</div><nav>{nav.map((n,i)=><a className={i===0?"active":""} key={n}>{n}</a>)}</nav><div className="sidefoot"><i/> System Online<br/><b>Vercel · Drive · CMS</b></div></aside>
 <section className="content"><header><div><small>HCDECOR / COMMAND CENTER</small><h1>Chào buổi sáng, HCDecor</h1><p>Quản lý dự án, nội dung và tự động hóa trong một không gian.</p></div><div className="actions"><button>Tìm kiếm</button><button className="primary">+ Tạo mới</button></div></header>
 <div className="notice"><span>DEMO V2</span> CMS: <b>{cms.read.ok?"Đã kết nối":"Chờ kết nối"}</b> · Drive: <b>Đã ánh xạ</b> · Publish: <b>Review trước khi đăng</b></div>
 <div className="kpis"><Card t="Projects" v="12" s="Đang vận hành"/><Card t="Automation Queue" v="8" s="3 đang xử lý"/><Card t="CMS / Drive" v={cms.read.ok?"2/2":"1/2"} s="Kết nối dữ liệu"/><Card t="Review" v="5" s="Chờ duyệt"/></div>
 <section className="panel"><div className="panelHead"><div><small>WORKFLOW</small><h2>Luồng vận hành nội dung</h2></div><span className="live">● LIVE</span></div><div className="flow">{["Tạo Project","Media / Drive","AI xử lý","Review","Web Publish","Đa kênh","Báo cáo"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div></section>
 <div className="grid"><section className="panel"><div className="panelHead"><div><small>QUEUE</small><h2>Công việc gần đây</h2></div><button>Xem tất cả</button></div><table><thead><tr><th>Công việc</th><th>Kênh</th><th>Trạng thái</th></tr></thead><tbody>{queue.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c}>{i===2?<span className="status">{c}</span>:c}</td>)}</tr>)}</tbody></table></section>
 <section className="panel"><div className="panelHead"><div><small>RUNTIME</small><h2>Kết nối hệ thống</h2></div></div><Conn n="Google Drive" s="connected"/><Conn n="WordPress CMS" s={cms.read.ok?"connected":"action_required"}/><Conn n="AI / Agent" s="demo"/><Conn n="Social API" s="later"/></section></div>
 <section className="panel calendar"><div className="panelHead"><div><small>CONTENT CALENDAR</small><h2>Lịch xuất bản tuần</h2></div><button>+ Lên lịch</button></div><div className="days">{["T2","T3","T4","T5","T6","T7","CN"].map((d,i)=><div key={d}><b>{d}</b>{i===1&&<article>09:00 · Facebook<br/><strong>Before / After</strong></article>}{i===3&&<article>14:30 · Website<br/><strong>Case Study</strong></article>}{i===5&&<article>20:00 · Media<br/><strong>Project Reel</strong></article>}</div>)}</div></section></section></main>}
function Card({t,v,s}){return <div className="card"><small>{t}</small><strong>{v}</strong><span>{s}</span></div>}
function Conn({n,s}){const ok=s==="connected";return <div className="conn"><span>{n}</span><b className={ok?"ok":""}>{ok?"Connected":s==="demo"?"Demo Ready":s==="later"?"Giai đoạn cuối":"Cần cấu hình"}</b></div>}
