import {promises as fs} from "node:fs";import path from "node:path";
const DIR=path.join(process.cwd(),".runtime");const FILE=path.join(DIR,"master-approvals.json");const MAX=100;
async function rows(){try{const x=JSON.parse(await fs.readFile(FILE,"utf8"));return Array.isArray(x)?x:[]}catch{return []}}
async function save(x){await fs.mkdir(DIR,{recursive:true});await fs.writeFile(FILE,JSON.stringify(x.slice(-MAX),null,2),"utf8")}
export async function queueApproval(plan){if(!plan?.execution?.requires_approval)return null;const all=await rows();const existing=all.find(x=>x.request_id===plan.request_id);if(existing)return existing;const item={request_id:plan.request_id,event_id:plan.audit.event_id,workspace_id:plan.workspace.workspace_id,site_id:plan.workspace.site_id,module:plan.task.module,action:plan.task.action,intent:plan.task.intent,status:"pending",created_at:plan.audit.timestamp,approved_at:null};all.push(item);try{await save(all);return item}catch{return null}}
export async function listApprovals(workspaceId="",limit=30){const w=typeof workspaceId==="string"?workspaceId.trim().toLowerCase().slice(0,80):"";const n=Math.max(1,Math.min(Number.isFinite(limit)?Math.trunc(limit):30,100));const all=await rows();return (w?all.filter(x=>x.workspace_id===w):all).slice(-n).reverse()}
export async function getApproval(requestId){const id=typeof requestId==="string"?requestId.trim().slice(0,80):"";if(!id)return null;const all=await rows();return all.find(x=>x.request_id===id)||null}
export async function rejectRequest(requestId){const id=typeof requestId==="string"?requestId.trim().slice(0,80):"";if(!id)return null;const all=await rows();const i=all.findIndex(x=>x.request_id===id);if(i<0)return null;if(all[i].status!=="pending")return all[i];all[i]={...all[i],status:"rejected",rejected_at:new Date().toISOString()};try{await save(all);return all[i]}catch{return null}}
export async function expireStaleApprovals(maxAgeHours=72){const hours=Math.max(1,Math.min(Number.isFinite(maxAgeHours)?maxAgeHours:72,720));const cutoff=Date.now()-hours*3600000;const all=await rows();let changed=0;for(let i=0;i<all.length;i++){if(all[i]?.status==="pending"&&Date.parse(all[i].created_at)<cutoff){all[i]={...all[i],status:"expired",expired_at:new Date().toISOString()};changed++}}if(changed)try{await save(all)}catch{return 0}return changed}
export async function approvalStats(){const all=await rows();return {total:all.length,pending:all.filter(x=>x.status==="pending").length,approvedNotExecuted:all.filter(x=>x.status==="approved-not-executed").length,rejected:all.filter(x=>x.status==="rejected").length,expired:all.filter(x=>x.status==="expired").length}}
export async function approveRequest(requestId){const id=typeof requestId==="string"?requestId.trim().slice(0,80):"";if(!id)return null;const all=await rows();const i=all.findIndex(x=>x.request_id===id);if(i<0)return null;if(all[i].status!=="pending")return all[i];all[i]={...all[i],status:"approved-not-executed",approved_at:new Date().toISOString()};try{await save(all);return all[i]}catch{return null}}
