import assert from 'node:assert/strict';
import {scheduleResourceAware,GOVERNOR_STATES,isTerminalState} from '../lib/governor/resource-scheduler.mjs';
let pass=0; const t=(name,fn)=>{fn(); pass++; console.log('PASS',name)};
const now=Date.parse('2026-10-02T15:00:00Z');

t('parallel ready work dispatches to free workers',()=>{const r=scheduleResourceAware({now,resources:{cpu:4},workers:[{worker_id:'w1',capabilities:['code'],concurrency_limit:1},{worker_id:'w2',capabilities:['code'],concurrency_limit:1}],tasks:[{task_id:'a',state:'READY',required_capabilities:['code'],resources:{cpu:1}},{task_id:'b',state:'READY',required_capabilities:['code'],resources:{cpu:1}}]});assert.equal(r.dispatches.length,2);});
t('dependency wait does not stall unrelated ready work',()=>{const r=scheduleResourceAware({resources:{cpu:2},completed_task_ids:[],workers:[{worker_id:'w',capabilities:['code'],concurrency_limit:1}],tasks:[{task_id:'blocked',state:'READY',depends_on:['x'],required_capabilities:['code'],resources:{cpu:1}},{task_id:'free',state:'READY',required_capabilities:['code'],resources:{cpu:1}}]});assert.deepEqual(r.waiting_dependency,['blocked']);assert.equal(r.dispatches[0].task_id,'free');});
t('resource saturation reports WAITING_RESOURCE not failure',()=>{const r=scheduleResourceAware({resources:{gpu:0,cpu:2},workers:[{worker_id:'w',capabilities:['render','code'],concurrency_limit:2}],tasks:[{task_id:'render',state:'READY',required_capabilities:['render'],resources:{gpu:1}},{task_id:'code',state:'READY',required_capabilities:['code'],resources:{cpu:1}}]});assert.deepEqual(r.waiting_resource,['render']);assert.equal(r.dispatches[0].task_id,'code');});
t('critical lane wins bounded capacity',()=>{const r=scheduleResourceAware({resources:{cpu:1},workers:[{worker_id:'w',capabilities:['code'],concurrency_limit:1}],tasks:[{task_id:'bulk',state:'READY',lane:'normal',priority:100,required_capabilities:['code'],resources:{cpu:1}},{task_id:'critical',state:'READY',lane:'critical',priority:1,required_capabilities:['code'],resources:{cpu:1}}]});assert.equal(r.dispatches[0].task_id,'critical');});
t('age breaks equal priority ties',()=>{const r=scheduleResourceAware({now,resources:{cpu:1},workers:[{worker_id:'w',capabilities:['code'],concurrency_limit:1}],tasks:[{task_id:'new',state:'READY',priority:5,ready_since:'2026-10-02T14:59:00Z',required_capabilities:['code'],resources:{cpu:1}},{task_id:'old',state:'READY',priority:5,ready_since:'2026-10-02T13:00:00Z',required_capabilities:['code'],resources:{cpu:1}}]});assert.equal(r.dispatches[0].task_id,'old');});
t('governor state contract includes safe terminals',()=>{for(const s of ['WAITING_RESOURCE','DONE','OWNER_REQUIRED','SAFETY_STOP','HARD_BLOCKED']) assert.ok(GOVERNOR_STATES.includes(s)); assert.ok(isTerminalState('DONE'));assert.equal(isTerminalState('RUNNING'),false);});

t('unregistered resource fails closed without stalling unrelated work',()=>{const r=scheduleResourceAware({resources:{cpu:2},workers:[{worker_id:'w',capabilities:['code','api'],concurrency_limit:2}],tasks:[{task_id:'api',state:'READY',required_capabilities:['api'],resources:{api_credit:1}},{task_id:'code2',state:'READY',required_capabilities:['code'],resources:{cpu:1}}]});assert.deepEqual(r.waiting_resource,['api']);assert.equal(r.dispatches[0].task_id,'code2');});
console.log(`GOVERNOR_RESOURCE_SCHEDULER_PASS ${pass}/7`);
