import fs from 'node:fs';import assert from 'node:assert/strict';
const bat=fs.readFileSync('hc-group-done.bat','utf8');
const ps=fs.readFileSync('scripts/hc-group-done.ps1','utf8');
const canonical=fs.readFileSync('HC-DONE.bat','utf8');
assert.ok(bat.includes('HC GROUP DONE'));
assert.ok(bat.includes('scripts\\hc-group-done.ps1'));
for(const lane of ['core','governor','evidence','registry','tools','portfolio']) assert.ok(ps.includes("Name='"+lane+"'"),lane);
assert.ok(ps.includes('Start-Process'));
assert.ok(ps.includes('$r.Process.WaitForExit()'));
assert.ok(ps.includes('$r.Process.Refresh()'));
assert.ok(ps.includes('HC_DONE_EXITCODE_UNAVAILABLE'));
assert.ok(ps.includes('$code=901'));
assert.ok(ps.includes('test:autodebug-implementation'));
assert.ok(ps.includes('research-request.json'));
assert.ok(ps.includes('approved plugins/web research'));
assert.ok(ps.includes("final_state='DONE'"));
assert.ok(ps.includes("execution_mode='LOCAL_FIRST'"));
assert.ok(ps.includes("compute_provider='HOCUONG_LAPTOP'"));
assert.ok(ps.includes("github_sync='ASYNC_NON_BLOCKING'"));
assert.ok(ps.includes("scripts\\hc-local-first.ps1 -Mode build"));
assert.ok(ps.includes("github_sync_required_for_done=$false"));
assert.ok(ps.includes('npm run test:master'));
assert.ok(ps.includes('production-smoke.ps1'));
assert.ok(ps.includes('HC_GROUP_DONE_PASS'));
assert.ok(canonical.includes('HC-LOCAL-FIRST.bat'));
assert.ok(canonical.includes('GitHub sync is non-blocking'));
console.log('HC_GROUP_DONE_PACKAGE_PASS launcher=1 parallel_lanes=6 autodebug=1 research_handoff=1 local_first=1 github_non_blocking=1 final_gate=1');
