import assert from 'node:assert/strict';
import fs from 'node:fs';
import {v9Readiness,finalGate} from '../lib/v9-final-preflight.mjs';

const m=JSON.parse(fs.readFileSync('config/hcdecor-v9-package-manifest.json','utf8'));
for(const x of m.packages) assert.equal(x.state,'DONE',x.id);
const p16=m.packages.find(x=>x.id==='PKG-16');
assert.equal(m.status,'DONE');
assert.equal(p16.evidence?.regression_suite,'PASS');
assert.equal(p16.evidence?.production_build,'PASS');
assert.equal(p16.evidence?.master_e2e,'PASS');
assert.equal(p16.evidence?.cloudflare_build,'PASS');
assert.equal(p16.evidence?.evidence_complete,true);
assert.equal(p16.evidence?.terminal_freeze,'PASS');
assert.equal(p16.evidence?.v9_frozen_done,true);
const r=v9Readiness();
assert.equal(r.done,17);
assert.equal(r.release_ready,true);
assert.equal(finalGate(r).pass,true);
assert.equal(finalGate(r).status,'V9_FROZEN_DONE');
console.log('HCDECOR_V9_RELEASE_FREEZE_PASS done=17/17 regression=1 production=1 e2e=1 cloudflare=1 frozen=1');
