import fs from 'node:fs';import assert from 'node:assert/strict';
const install=fs.readFileSync('tools/hcdr-relay/install-always-on.ps1','utf8');
const watchdog=fs.readFileSync('tools/hcdr-relay/watchdog.ps1','utf8');
const bat=fs.readFileSync('hcdr-install-always-on.bat','utf8');
const userSupervisor=fs.readFileSync('tools/hcdr-relay/user-supervisor.ps1','utf8');
assert.ok(install.includes('New-ScheduledTaskTrigger -AtStartup'));
assert.ok(install.includes('New-ScheduledTaskTrigger -AtLogOn'));
assert.ok(install.includes('-RestartCount 999'));
assert.ok(install.includes('HCDR_ALWAYS_ON_INSTALLED'));
assert.ok(install.includes('HCDecor-HCDR-Supervisor.bat.disabled'));
assert.ok(install.includes('HCDRV11Relay'));
assert.ok(install.includes('startup-supervisor'));
assert.ok(install.includes('HCDR_ALWAYS_ON_FALLBACK_STARTUP'));
assert.ok(install.includes('user-supervisor.ps1'));
assert.ok(watchdog.includes('hcdr-relay-heartbeat.json'));
assert.ok(watchdog.includes('StaleSeconds'));
assert.ok(watchdog.includes('HCDR_WATCHDOG_RESTARTED'));
assert.ok(watchdog.includes('hcdr-relay.lock'));
assert.ok(bat.includes('install-always-on.ps1'));
assert.ok(userSupervisor.includes('hcdr-user-supervisor-heartbeat.json'));
assert.ok(userSupervisor.includes('watchdog.ps1'));
console.log('HCDR_ALWAYS_ON_CONTRACT_PASS boot=1 logon=1 watchdog=1 heartbeat=1 restart=1');
