import assert from 'node:assert/strict';
import fs from 'node:fs';
const p='config/imaster-skills/local-first-execution.json';
const s=JSON.parse(fs.readFileSync(p));
const boot=JSON.parse(fs.readFileSync('config/imaster-bootstrap.json'));
const reg=JSON.parse(fs.readFileSync('config/capability-registry.json'));
const auth=JSON.parse(fs.readFileSync('config/imaster-global-authority.json'));
const route=['CODE','HOCUONG_LOCAL_DIRECT_OR_LOCAL_EXECUTOR','LOCAL_BUILD_OR_RUN','ONE_REAL_TARGETED_TEST','LOCAL_PASS','USE_OR_DONE','GITHUB_SYNC_OR_CI_ONLY_WHEN_NEEDED'];
assert.equal(s.autoload,true);
assert.deepEqual(s.route,route);
assert.equal(s.authority_rule,'LOCAL_REAL_TEST_PASS_IS_AUTHORITATIVE');
assert.deepEqual(s.github_minimal_verify,['COMMIT_HASH','PASS_MANIFEST','INTEGRITY','SMOKE']);
assert.equal(s.deep_verify.default,false);
assert.equal(s.enforcement.github_replay_after_local_pass,'FORBIDDEN_UNLESS_RISK_OR_ANOMALY_REQUIRES_IT');
assert.equal(s.transport_priority[0].transport,'LOCAL_DIRECT_OR_LOCAL_EXECUTOR');
assert.equal(s.transport_priority[0].priority,1);
assert.equal(s.transport_priority[1].transport,'HCDR');
assert.equal(s.transport_priority[1].role,'FALLBACK_AND_RECOVERY');
assert.equal(s.transport_priority[2].transport,'RDC');
assert.equal(s.transport_priority[2].role,'RESCUE_ONLY');
assert.ok(boot.load_order.includes(p));
assert.ok(boot.skill_autoload.includes(p));
for(const law of ['LOCAL_FIRST_OPERATING_LAW','LOCAL_PASS_AUTHORITATIVE','GITHUB_MINIMAL_VERIFY','GITHUB_MUST_NOT_REPLAY_PASSED_LOCAL_GATES']) assert.ok(boot.mandatory_laws.includes(law));
for(const law of ['LOCAL_FIRST_OPERATING_LAW','LOCAL_PASS_AUTHORITATIVE','GITHUB_MINIMAL_VERIFY','DO_NOT_REDO_PASS']) assert.ok(auth.laws.includes(law));
assert.equal(auth.status,'PUBLIC');
assert.equal(auth.operating_law_local_first.status,'MANDATORY');
assert.ok(Array.isArray(auth.operating_law_local_first.route));
assert.equal(auth.operating_law_local_first.local_pass_authority,'AUTHORITATIVE');
assert.equal(auth.operating_law_local_first.github_policy.role,'MINIMAL_CONFIRMATION_ONLY');
assert.equal(auth.operating_law_local_first.github_policy.replay_passed_local_gates,'FORBIDDEN_UNLESS_DEEP_VERIFY');
assert.equal(auth.operating_law_local_first.rdc_policy,'RESCUE_ONLY_AFTER_HCDR_FAILURE_EVIDENCE');
assert.equal(auth.operating_law_local_first.hcdr_policy.first_attempt_required,true);
const cap=reg.capabilities.find(x=>x.capability_id==='imaster.local-first-execution');
assert.ok(cap);
assert.ok(Array.isArray(cap.transport_priority));
console.log('IMASTER_LOCAL_FIRST_SKILL_PASS local_authoritative=1 github_minimal_verify=1 no_replay=1 hcdr_primary=1 rdc_rescue=1 autoload=1');
