const base=process.env.HCDECOR_E2E_BASE||"http://localhost:3219";const headers={"content-type":"application/json",origin:base,"sec-fetch-site":"same-origin","x-hcdecor-test":"master-e2e"};let failed=0;async function post(path,body){const r=await fetch(base+path,{method:"POST",headers,body:JSON.stringify(body)});let x={};try{x=await r.json()}catch{}return {status:r.status,x}}function check(name,ok,detail=""){console.log((ok?"PASS":"FAIL"),name,detail);if(!ok)failed++}
for(const m of ["content","media","publishing"]){const r=await post("/api/master",{workspace_id:"hcdecor",module:m,action:"create",intent:"regression "+m,execute:true,test_mode:true});check(m+" preview",r.status===201&&r.x.execution?.mode==="preview-only"&&r.x.execution?.data?.production_write===false,r.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"website",action:"create",intent:"must block",execute:true,test_mode:true});check("website create blocked",r.status===409,r.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"publishing",action:"publish",intent:"must require approval",execute:true,test_mode:true});check("publish guarded",r.status===403&&r.x.plan?.execution?.requires_approval===true,r.status)}
{const r=await post("/api/master/batch",{test_mode:true,tasks:[{workspace_id:"hcdecor",module:"reports",action:"create",intent:"must block batch"}]});check("batch mutation blocked",r.status===409,r.status);const br=await post("/api/master/batch",{test_mode:true,tasks:[{workspace_id:"hcdecor",module:"agents",action:"view",intent:"parallel a"},{workspace_id:"gsc-senior",module:"digital_twin",action:"view",intent:"parallel b"}]});check("batch parallel read policy",br.status===200&&br.x.parallel===true&&br.x.parallel_policy==="read-only-independent-tasks"&&br.x.same_resource_writes==="not-accepted"&&br.x.production_write===false&&br.x.count===2,br.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"website",action:"view",intent:"bad capability",capability:"content",test_mode:true});check("capability mismatch blocked",r.status===400,r.status)}
{const r=await post("/api/master/workflows/preview",{workspace_id:"hcdecor",intent:"workflow regression",test_mode:true});check("preview workflow",r.status===201&&r.x.status==="preview-ready"&&r.x.execution_model==="dag"&&r.x.stages?.[0]?.parallel_safe===true&&r.x.stages?.[0]?.execution==="sequential-local-spool"&&r.x.stages?.[0]?.modules?.includes("content")&&r.x.stages?.[0]?.modules?.includes("media")&&r.x.steps?.length===3&&r.x.steps?.find(s=>s.module==="content")?.artifact?.type==="content-brief"&&r.x.steps?.find(s=>s.module==="publishing")?.artifact?.publish===false&&r.x.production_write===false,r.status);const a=await fetch(base+"/api/master/workflows/artifacts?workflow_id="+encodeURIComponent(r.x.workflow_id));const ax=await a.json();check("workflow artifact completeness",a.status===200&&ax.completeness?.complete===true&&ax.completeness?.missing?.length===0,a.status)}
{const w=await post("/api/master/workflows/preview",{workspace_id:"hcdecor",intent:"review boundary regression",project_id:"P-READ-MISSING",test_mode:true});const id=w.x.workflow_id;check("project context degrades without blocking",w.status===201&&w.x.context_state==="unavailable"&&w.x.context_durable===false,w.status);const rv=await post("/api/master/workflows/review",{workflow_id:id,status:"ready-for-review",confirm:true,test_mode:true});check("review is not production approval",rv.status===200&&rv.x.review?.production_approval===false&&rv.x.review?.test_mode===true&&rv.x.production_approval===false&&rv.x.production_authority===false&&rv.x.production_execution_started===false,rv.status)}
{const g=await fetch(base+"/api/master/workflows/review?workflow_id=does-not-exist");const gx=await g.json();check("unknown workflow review GET blocked",g.status===404&&gx.error==="workflow_not_found",g.status);const rv=await post("/api/master/workflows/review",{workflow_id:"does-not-exist",status:"ready-for-review",confirm:true});check("unknown workflow review blocked",rv.status===404&&rv.x.error==="workflow_not_found",rv.status)}
for(const [w,adapter] of [["gsc-senior","vercel-github"],["amo-nguyen","vercel-github"]]){const r=await fetch(base+"/api/master/preflight?workspace="+w);const x=await r.json();const site=x.modules?.find(v=>v.module==="website");check(w+" website adapter",r.status===200&&site?.adapter===adapter&&site?.config_state==="configured-source",site?.config_state||r.status)}
{const r=await fetch(base+"/api/master/approvals?limit=1");const x=await r.json();check("approval GET is read-only surface",r.status===200&&Array.isArray(x.approvals),r.status);const bad=await post("/api/master/approvals",{request_id:"does-not-exist",confirm:true,decision:"invalid"});check("approval decision fails closed",bad.status===400&&bad.x.error==="invalid_approval_decision",bad.status)}
{const r=await fetch(base+"/api/master/readiness");const x=await r.json();check("master readiness truth contract",r.status===200&&x.workspaces?.length===3&&x.truth_contract?.production_write===false&&x.truth_contract?.local_spool_is_production_authority===false,r.status)}
{const r=await fetch(base+"/api/master/readiness?live=1");const x=await r.json();check("live readiness probes fixed workspace sites",r.status===200&&x.live_probe===true&&x.workspaces?.every(w=>w.live_health?.state&&w.production_write===false),r.status)}
{const r=await fetch(base+"/api/deploy",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const x=await r.json();check("deploy mutation requires origin guard",r.status===403&&x.error==="missing_origin_context",r.status)}
{const r=await fetch(base+"/api/publishing/jobs",{method:"DELETE",headers:{origin:"https://invalid.example","content-length":"2"},body:"{}"});const x=await r.json();check("retired publishing mutation blocks cross origin",r.status===403&&x.error==="cross_origin_mutation_blocked",r.status)}
for(const [w,m] of [["gsc-senior","digital_twin"],["amo-nguyen","catalog"]]){const r=await post("/api/master",{workspace_id:w,module:m,action:"view",intent:"workspace module smoke",execute:true,test_mode:true});check(w+" module smoke",r.status===200&&r.x.plan?.task?.module===m&&r.x.execution?.verification?.passed===true,r.status)}
{const r=await fetch(base+"/api/master/smoke");const x=await r.json();check("workspace smoke center",r.status===200&&x.ok===true&&x.parallel===true&&Number.isFinite(x.elapsed_ms)&&x.production_write===false&&x.live_provider_execution===false&&x.workspaces?.length===3&&x.workspaces.every(w=>w.routing?.route_ok&&w.routing?.worker&&w.adapter_readiness?.source&&w.adapter_readiness?.runtime&&w.production_write===false),r.status)}
{const r=await fetch(base+"/api/master/previews?workspace=hcdecor&limit=100");const x=await r.json();check("preview listing hides test artifacts",r.status===200&&Array.isArray(x.previews)&&x.previews.every(p=>p.test_mode!==true),r.status)}
{const r=await fetch(base+"/api/master/runs?workspace=hcdecor&limit=100");const x=await r.json();check("run listing hides test runs",r.status===200&&Array.isArray(x.runs)&&x.runs.every(v=>v.test_mode!==true),r.status)}
{const r=await fetch(base+"/api/master/workflows?workspace=hcdecor&limit=5");const x=await r.json();check("recent workflow lookup is local authority false",r.status===200&&Array.isArray(x.workflows)&&x.production_authority===false&&x.workflows.every(w=>w.production_authority===false),r.status)}
{const r=await fetch(base+"/api/runtime");const x=await r.json();check("runtime capabilities expose booleans only",r.status===200&&x.capabilityContract?.booleanOnly===true&&x.capabilityContract?.secretsExposed===false&&x.capabilityContract?.productionWrite===false&&Object.values(x.capabilities||{}).every(v=>typeof v==="boolean")&&x.masterRuntime?.productionWrite===false,r.status)}
{const r=await fetch(base+"/api/master/actions");const x=await r.json();const guarded=new Set((x.actions||[]).filter(a=>a.guarded).map(a=>a.action));check("master action catalog exposes production guards",r.status===200&&x.production_write===false&&["publish","delete","manage","deploy","rollback"].every(a=>guarded.has(a)),r.status)}
{const r=await fetch(base+"/api/master/architecture");const x=await r.json();check("architecture baseline is locked",r.status===200&&x.baseline?.status==="locked"&&x.baseline?.principle==="core-stable-edge-flexible"&&x.production_write===false,r.status);const edge=await post("/api/master/architecture",{requested_change:"Vercel to another provider",affected_components:["deployment-provider"]});const core=await post("/api/master/architecture",{requested_change:"replace master planner",affected_components:["master-agent","planner-task-dag"]});check("architecture change warning contract",edge.status===200&&edge.x.warning_required===false&&edge.x.classification==="edge-adapter-change"&&core.status===200&&core.x.warning_required===true&&core.x.explicit_confirmation_required===true&&core.x.classification==="architecture-core-change",core.status)}
{const r=await post("/api/master/dag",{workspace_id:"hcdecor",tasks:[{task_id:"read-a",module:"agents",action:"view",intent:"read runtime"},{task_id:"read-b",module:"reports",action:"view",intent:"read reports"},{task_id:"deploy-c",module:"website",action:"deploy",intent:"deploy only after checks",depends_on:["read-a","read-b"]}]});check("task dag plans dependencies without execution",r.status===200&&r.x.stages?.length===2&&r.x.stages?.[0]?.parallel_safe===true&&r.x.requires_approval===true&&r.x.production_write===false&&r.x.execution_started===false,r.status);const c=await post("/api/master/dag",{workspace_id:"hcdecor",tasks:[{task_id:"a",module:"agents",action:"view",intent:"a",depends_on:["b"]},{task_id:"b",module:"agents",action:"view",intent:"b",depends_on:["a"]}]});check("task dag rejects dependency cycles",c.status===400&&c.x.error==="dependency_cycle",c.status)}
{for(const [w,p] of [["hcdecor","wordpress"],["gsc-senior","vercel"],["amo-nguyen","vercel"]]){const r=await fetch(base+"/api/master/deployment?workspace="+w);const x=await r.json();check(w+" deployment adapter",r.status===200&&x.providers?.primary?.provider===p&&x.provider_change==="adapter-change-not-core-change"&&x.deploy_requires_approval===true&&x.production_write===false,p)}const plan=await post("/api/master/deployment",{workspace_id:"gsc-senior",environment:"production"});check("production deployment stays plan-only",plan.status===200&&plan.x.provider==="vercel"&&plan.x.requires_approval===true&&plan.x.execution_started===false&&plan.x.production_write===false,plan.status);const bad=await post("/api/master/deployment",{workspace_id:"gsc-senior",provider:"cloudflare",environment:"production"});check("unconfigured deployment provider blocked",bad.status===400&&bad.x.error==="deployment_provider_not_configured",bad.status)}
{const a=await fetch(base+"/api/master/capabilities?workspace=hcdecor&module=website&action=view");const ax=await a.json();check("capability router resolves website worker",a.status===200&&ax.capability==="website"&&ax.worker==="website"&&ax.production_write===false&&ax.production_execution_started===false,a.status);const b=await fetch(base+"/api/master/capabilities?workspace=amo-nguyen&module=reports&action=view");const bx=await b.json();check("capability router is workspace aware",b.status===200&&bx.capability==="report"&&bx.worker==="project-assistant"&&bx.workspace_id==="amo-nguyen",b.status);const c=await fetch(base+"/api/master/capabilities?workspace=hcdecor&module=website&capability=deployment&action=deploy");const cx=await c.json();check("capability router keeps deployment gated",c.status===200&&cx.requires_approval===true&&cx.production_write==="approval-required"&&cx.production_execution_started===false,c.status)}
{const r=await fetch(base+"/api/master/operational");const x=await r.json();check("operational contract reports locked source-ready skeleton",r.status===200&&x.architecture?.status==="locked"&&x.summary?.workspaces===3&&x.summary?.source_ready===3&&x.summary?.operational_skeleton_ready===true&&x.truth_contract?.production_write===false&&x.workspaces?.every(w=>w.production_write===false),r.status);check("operational contract separates read from durable write runtime",Object.values(x.capabilities||{}).every(v=>typeof v==="boolean")&&x.summary?.read_capabilities===1&&x.summary?.write_capabilities===0&&x.workspaces?.find(w=>w.workspace_id==="hcdecor")?.runtime_read_ready===true&&x.workspaces?.find(w=>w.workspace_id==="hcdecor")?.durable_write_runtime_ready===false,x.summary?.write_capabilities)}
{const r=await fetch(base+"/api/master/verify-all");const x=await r.json();check("cross-workspace operational verification",[200,409].includes(r.status)&&x.source_verified===true&&((r.status===200&&x.ok===true&&x.live_verified===true&&x.status==="verified")||(r.status===409&&x.ok===false&&x.live_verified===false&&x.status==="source-ready-live-degraded"))&&x.parallel===true&&x.workspaces?.length===3&&x.workspaces?.every(w=>w.routing?.ok&&w.deployment?.ok&&w.deployment?.requires_approval===true&&w.production_write===false)&&x.production_execution_started===false,r.status)}
{const r=await fetch(base+"/api/runtime/diagnostics");const x=await r.json();const reqs=Object.values(x.requirements||{});check("runtime diagnostics expose requirements without secrets",r.status===200&&x.secrets_exposed===false&&x.credentials_validated===false&&x.production_write===false&&x.total===6&&x.setup_order?.length===6&&(x.next_requirement===null||Array.isArray(x.next_requirement?.missing))&&reqs.every(v=>typeof v.ready==="boolean"&&Array.isArray(v.missing)&&v.missing.every(n=>typeof n==="string"&&/^[A-Z0-9_]+$/.test(n))),r.status)}
{const r=await fetch(base+"/api/cms/status");const x=await r.json();check("wordpress public read adapter is live without write credential",r.status===200&&x.provider==="wordpress"&&x.config?.read===true&&x.config?.writeCredential===false&&x.config?.writeMode==="read-only"&&x.liveHealth==="healthy"&&x.probe?.ok===true&&x.runtimePlugin?.installed===true&&x.runtimePlugin?.status==="installed"&&x.sourceProductionDrift===false&&x.production_write===false,r.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"website",action:"view",intent:"verify live wordpress read",execute:true,test_mode:true});check("master executes live wordpress website read",r.status===200&&r.x.execution?.mode==="read-only"&&r.x.execution?.data?.source?.adapter==="wordpress"&&r.x.execution?.data?.live?.ok===true&&r.x.execution?.verification?.passed===true,r.status)}
{const r=await fetch(base+"/api/cms/inventory");const x=await r.json();check("wordpress content inventory is read only",r.status===200&&x.ok===true&&Number.isFinite(x.posts?.count)&&Number.isFinite(x.pages?.count)&&x.production_write===false,r.status)}
{for(const w of ["gsc-senior","amo-nguyen"]){const r=await post("/api/master",{workspace_id:w,module:"website",action:"view",intent:"verify live web page",execute:true,test_mode:true});check(w+" master website probe verifies html",r.status===200&&r.x.execution?.data?.live?.ok===true&&r.x.execution?.data?.live?.content_type==="text/html"&&r.x.execution?.data?.live?.production_write===false&&r.x.execution?.verification?.passed===true,r.status)}}
{const r=await fetch(base+"/api/runtime/diagnostics");const x=await r.json();check("verified data authorities configure ids without enabling writes",r.status===200&&x.capabilities?.driveConfigured===true&&x.capabilities?.driveWrite===false&&x.capabilities?.leadWrite===false&&x.capabilities?.projectWrite===false&&x.requirements?.driveConfigured?.missing?.length===0,r.status)}
process.exitCode=failed?1:0;
