const base=process.env.HCDECOR_E2E_BASE||"http://localhost:3219";const headers={"content-type":"application/json",origin:base,"sec-fetch-site":"same-origin"};let failed=0;async function post(path,body){const r=await fetch(base+path,{method:"POST",headers,body:JSON.stringify(body)});let x={};try{x=await r.json()}catch{}return {status:r.status,x}}function check(name,ok,detail=""){console.log((ok?"PASS":"FAIL"),name,detail);if(!ok)failed++}
for(const m of ["content","media","publishing"]){const r=await post("/api/master",{workspace_id:"hcdecor",module:m,action:"create",intent:"regression "+m,execute:true,test_mode:true});check(m+" preview",r.status===201&&r.x.execution?.mode==="preview-only"&&r.x.execution?.data?.production_write===false,r.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"website",action:"create",intent:"must block",execute:true,test_mode:true});check("website create blocked",r.status===409,r.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"publishing",action:"publish",intent:"must require approval",execute:true,test_mode:true});check("publish guarded",r.status===403&&r.x.plan?.execution?.requires_approval===true,r.status)}
{const r=await post("/api/master/batch",{tasks:[{workspace_id:"hcdecor",module:"reports",action:"create",intent:"must block batch"}]});check("batch mutation blocked",r.status===409,r.status)}
{const r=await post("/api/master",{workspace_id:"hcdecor",module:"website",action:"view",intent:"bad capability",capability:"content",test_mode:true});check("capability mismatch blocked",r.status===400,r.status)}
{const r=await post("/api/master/workflows/preview",{workspace_id:"hcdecor",intent:"workflow regression"});check("preview workflow",r.status===201&&r.x.status==="preview-ready"&&r.x.steps?.length===3&&r.x.steps?.[0]?.artifact?.type==="content-brief"&&r.x.steps?.[2]?.artifact?.publish===false&&r.x.production_write===false,r.status);const a=await fetch(base+"/api/master/workflows/artifacts?workflow_id="+encodeURIComponent(r.x.workflow_id));const ax=await a.json();check("workflow artifact completeness",a.status===200&&ax.completeness?.complete===true&&ax.completeness?.missing?.length===0,a.status)}
{const w=await post("/api/master/workflows/preview",{workspace_id:"hcdecor",intent:"review boundary regression",project_id:"P-READ-MISSING"});const id=w.x.workflow_id;check("project context degrades without blocking",w.status===201&&w.x.context_state==="unavailable"&&w.x.context_durable===false,w.status);const rv=await post("/api/master/workflows/review",{workflow_id:id,status:"ready-for-review",confirm:true});check("review is not production approval",rv.status===200&&rv.x.review?.production_approval===false&&rv.x.production_execution_started===false,rv.status)}
{const g=await fetch(base+"/api/master/workflows/review?workflow_id=does-not-exist");const gx=await g.json();check("unknown workflow review GET blocked",g.status===404&&gx.error==="workflow_not_found",g.status);const rv=await post("/api/master/workflows/review",{workflow_id:"does-not-exist",status:"ready-for-review",confirm:true});check("unknown workflow review blocked",rv.status===404&&rv.x.error==="workflow_not_found",rv.status)}
for(const [w,adapter] of [["gsc-senior","vercel-github"],["amo-nguyen","vercel-github"]]){const r=await fetch(base+"/api/master/preflight?workspace="+w);const x=await r.json();const site=x.modules?.find(v=>v.module==="website");check(w+" website adapter",r.status===200&&site?.adapter===adapter&&site?.config_state==="configured-source",site?.config_state||r.status)}
{const r=await fetch(base+"/api/master/approvals?limit=1");const x=await r.json();check("approval GET is read-only surface",r.status===200&&Array.isArray(x.approvals),r.status)}
{const r=await fetch(base+"/api/master/readiness");const x=await r.json();check("master readiness truth contract",r.status===200&&x.workspaces?.length===3&&x.truth_contract?.production_write===false&&x.truth_contract?.local_spool_is_production_authority===false,r.status)}
{const r=await fetch(base+"/api/master/readiness?live=1");const x=await r.json();check("live readiness probes fixed workspace sites",r.status===200&&x.live_probe===true&&x.workspaces?.every(w=>w.live_health?.state&&w.production_write===false),r.status)}
{const r=await fetch(base+"/api/deploy",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const x=await r.json();check("deploy mutation requires origin guard",r.status===403&&x.error==="missing_origin_context",r.status)}
{const r=await fetch(base+"/api/publishing/jobs",{method:"DELETE",headers:{origin:"https://invalid.example","content-length":"2"},body:"{}"});const x=await r.json();check("retired publishing mutation blocks cross origin",r.status===403&&x.error==="cross_origin_mutation_blocked",r.status)}
for(const [w,m] of [["gsc-senior","digital_twin"],["amo-nguyen","catalog"]]){const r=await post("/api/master",{workspace_id:w,module:m,action:"view",intent:"workspace module smoke",execute:true,test_mode:true});check(w+" module smoke",r.status===200&&r.x.plan?.task?.module===m&&r.x.execution?.verification?.passed===true,r.status)}
{const r=await fetch(base+"/api/master/smoke");const x=await r.json();check("workspace smoke center",r.status===200&&x.ok===true&&x.production_write===false&&x.workspaces?.length===3&&x.workspaces.every(w=>w.routing?.route_ok&&w.adapter_readiness?.source&&w.adapter_readiness?.runtime&&w.production_write===false),r.status)}
{const r=await fetch(base+"/api/master/workflows?workspace=hcdecor&limit=5");const x=await r.json();check("recent workflow lookup is local authority false",r.status===200&&Array.isArray(x.workflows)&&x.production_authority===false&&x.workflows.every(w=>w.production_authority===false),r.status)}
process.exitCode=failed?1:0;
