import fs from 'node:fs';
import assert from 'node:assert/strict';
const helper=fs.readFileSync('lib/operator-telemetry.js','utf8');
const route=fs.readFileSync('app/api/master/operator-telemetry/route.js','utf8');
const page=fs.readFileSync('app/hub/operator/page.js','utf8');
assert.ok(helper.includes('masterRunStoreInfo'));
assert.ok(helper.includes('durableRuntimeStatus'));
assert.ok(helper.includes('DurableWorkerHeartbeatStore'));
assert.ok(helper.includes('DurableEvidenceStore'));
assert.ok(helper.includes('evidence-events.jsonl'));
assert.ok(helper.includes('recent_evidence'));
assert.ok(helper.includes('evidence_store_health'));
assert.ok(helper.includes('worker-heartbeats.json'));
assert.ok(helper.includes('suspect_workers'));
assert.ok(helper.includes('production_write:false'));
assert.ok(helper.includes('production_authority'));
assert.ok(helper.includes('capabilityRegistry'));
assert.ok(helper.includes('contract_state:c.contract_state||"baseline-gated"'));
assert.ok(helper.includes('production_authority:false'));
assert.ok(page.includes('telemetry.capabilities'));
assert.ok(page.includes('contract_state'));
assert.ok(page.includes('production authority'));
assert.ok(page.includes('RECENT EVIDENCE'));
assert.ok(page.includes('telemetry.recent_evidence'));
assert.ok(page.includes('telemetry.sources.evidence_events.authority'));


assert.ok(helper.includes('run_history:{authority:runStore.mode'),'run history authority must derive from store metadata');
assert.ok(helper.includes('worker_heartbeats:{authority:"local-spool",production_authority:false}'),'worker heartbeat local spool authority must be explicit and non-authoritative');
assert.ok(route.includes('operatorTelemetrySnapshot'));
assert.equal(/POST|PUT|PATCH|DELETE/.test(route),false);
assert.ok(page.includes('EVIDENCE STORE'));
assert.ok(page.includes('telemetry.evidence_store_health.state'));
assert.ok(page.includes('malformed'));
assert.ok(page.includes('rotation needed:'));
assert.ok(page.includes('evidence_store_health.bytes'));
assert.ok(page.includes('evidence_store_health.needs_rotation'));
assert.ok(page.includes('UNPROVEN TOOLS'));
assert.ok(page.includes('TOOL VERIFICATION'));
assert.ok(page.includes('verification_state'));
assert.ok(page.includes('not-proven-done'));
console.log('OPERATOR_TELEMETRY_PASS read_only=1 authority_labels=1 durable_status=1 run_history=1 worker_heartbeats=1');
